### ISSUE TITLE
 pytorch 用CPU训练报错

### ISSUE THREAD

**Issue by makehaha** [chineseocr/chinese-ocr#103]
因为使用虚机，没有NVIDIA 的显卡，启动的时候报错。请问如何解决？

loading pretrained model from ../pretrain-models/netCRNN.pth
Traceback (most recent call last):
  File "crnn_main.py", line 101, in <module>
    crnn.load_state_dict(torch.load(opt.crnn))
  File "/root/miniconda2/lib/python2.7/site-packages/torch/serialization.py", line 229, in load
    return _load(f, map_location, pickle_module)
  File "/root/miniconda2/lib/python2.7/site-packages/torch/serialization.py", line 377, in _load
    result = unpickler.load()
  File "/root/miniconda2/lib/python2.7/site-packages/torch/serialization.py", line 348, in persistent_load
    data_type(size), location)
  File "/root/miniconda2/lib/python2.7/site-packages/torch/serialization.py", line 85, in default_restore_location
    result = fn(storage, location)
  File "/root/miniconda2/lib/python2.7/site-packages/torch/serialization.py", line 67, in _cuda_deserialize
    return obj.cuda(device_id)
  File "/root/miniconda2/lib/python2.7/site-packages/torch/_utils.py", line 57, in _cuda
    with torch.cuda.device(device):
  File "/root/miniconda2/lib/python2.7/site-packages/torch/cuda/__init__.py", line 124, in __enter__
    _lazy_init()
  File "/root/miniconda2/lib/python2.7/site-packages/torch/cuda/__init__.py", line 84, in _lazy_init
    _check_driver()
  File "/root/miniconda2/lib/python2.7/site-packages/torch/cuda/__init__.py", line 58, in _check_driver
    http://www.nvidia.com/Download/index.aspx""")
AssertionError: 
Found no NVIDIA driver on your system. Please check that you
have an NVIDIA GPU and installed a driver from
http://www.nvidia.com/Download/index.aspx

**Comment by makehaha** [comment]
keras-train 报错：
2018-02-16 10:50:31.361794: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: slice index 0 of dimension 0 out of bounds.
Traceback (most recent call last):
  File "trainbatch.py", line 35, in <module>
    model.train_on_batch( X,Y)  
  File "/root/miniconda2/lib/python2.7/site-packages/keras/engine/training.py", line 1762, in train_on_batch
    outputs = self.train_function(ins)
  File "/root/miniconda2/lib/python2.7/site-packages/keras/backend/tensorflow_backend.py", line 2273, in __call__
    **self.session_kwargs)
  File "/root/miniconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 895, in run
    run_metadata_ptr)
  File "/root/miniconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1124, in _run
    feed_dict_tensor, options, run_metadata)
  File "/root/miniconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1321, in _do_run
    options, run_metadata)
  File "/root/miniconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1340, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: slice index 0 of dimension 0 out of bounds.
	 [[Node: ctc/scan/strided_slice = StridedSlice[Index=DT_INT32, T=DT_INT32, begin_mask=0, ellipsis_mask=0, end_mask=0, new_axis_mask=0, shrink_axis_mask=1, _device="/job:localhost/replica:0/task:0/cpu:0"](ctc/scan/Shape, ctc/scan/strided_slice/stack, ctc/scan/strided_slice/stack_1, ctc/scan/strided_slice/stack_2)]]

Caused by op u'ctc/scan/strided_slice', defined at:
  File "trainbatch.py", line 3, in <module>
    model,basemodel = get_model(height=imgH, nclass=nclass)
  File "/root/crnn/chinese-ocr/train/keras-train/model.py", line 52, in get_model
    loss_out = Lambda(ctc_lambda_func, output_shape=(1,), name='ctc')([y_pred, labels, input_length, label_length])
  File "/root/miniconda2/lib/python2.7/site-packages/keras/engine/topology.py", line 602, in __call__
    output = self.call(inputs, **kwargs)
  File "/root/miniconda2/lib/python2.7/site-packages/keras/layers/core.py", line 650, in call
    return self.function(inputs, **arguments)
  File "/root/crnn/chinese-ocr/train/keras-train/model.py", line 15, in ctc_lambda_func
    return K.ctc_batch_cost(labels, y_pred, input_length, label_length)
  File "/root/miniconda2/lib/python2.7/site-packages/keras/backend/tensorflow_backend.py", line 3656, in ctc_batch_cost
    sparse_labels = tf.to_int32(ctc_label_dense_to_sparse(y_true, label_length))
  File "/root/miniconda2/lib/python2.7/site-packages/keras/backend/tensorflow_backend.py", line 3620, in ctc_label_dense_to_sparse
    initializer=init, parallel_iterations=1)
  File "/root/miniconda2/lib/python2.7/site-packages/tensorflow/python/ops/functional_ops.py", line 526, in scan
    n = array_ops.shape(elems_flat[0])[0]
  File "/root/miniconda2/lib/python2.7/site-packages/tensorflow/python/ops/array_ops.py", line 509, in _SliceHelper
    name=name)
  File "/root/miniconda2/lib/python2.7/site-packages/tensorflow/python/ops/array_ops.py", line 677, in strided_slice
    shrink_axis_mask=shrink_axis_mask)
  File "/root/miniconda2/lib/python2.7/site-packages/tensorflow/python/ops/gen_array_ops.py", line 3744, in strided_slice
    shrink_axis_mask=shrink_axis_mask, name=name)
  File "/root/miniconda2/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "/root/miniconda2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2630, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/root/miniconda2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1204, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): slice index 0 of dimension 0 out of bounds.
	 [[Node: ctc/scan/strided_slice = StridedSlice[Index=DT_INT32, T=DT_INT32, begin_mask=0, ellipsis_mask=0, end_mask=0, new_axis_mask=0, shrink_axis_mask=1, _device="/job:localhost/replica:0/task:0/cpu:0"](ctc/scan/Shape, ctc/scan/strided_slice/stack, ctc/scan/strided_slice/stack_1, ctc/scan/strided_slice/stack_2)]]
