### ISSUE TITLE
可否公开训练代码？

### ISSUE THREAD

**Issue by huang-aoyun** [chineseocr/chinese-ocr#11]
谢谢您的分享，可否公开训练代码？

**Comment by wenlihaoyu** [comment]
train 目录下有训练代码

**Comment by huang-aoyun** [comment]
谢谢您

--------------原始邮件--------------
发件人："lywen "<notifications@github.com>;
发送时间：2017年12月8日(星期五) 上午10:55
收件人："chineseocr/chinese-ocr" <chinese-ocr@noreply.github.com>;
抄送："huang-aoyun "<huang_aoyun@i-soon.net>;"Author "<author@noreply.github.com>;
主题：Re: [chineseocr/chinese-ocr] 可否公开训练代码？ (#11)
-----------------------------------

train 目录下有训练代码

**Comment by huang-aoyun** [comment]
谢谢

**Comment by gazibrother** [comment]
谢谢您的分享！我跑trainbatch.py程序时，遇到了这样的报错，请问怎么解决呢？
Traceback (most recent call last):
  File "trainbatch.py", line 33, in <module>
    model.train_on_batch( X,Y)  
  File "/usr/lib64/python2.7/site-packages/keras/engine/training.py", line 1756, in train_on_batch
    check_batch_axis=True)
  File "/usr/lib64/python2.7/site-packages/keras/engine/training.py", line 1390, in _standardize_user_data
    _check_array_lengths(x, y, sample_weights)
  File "/usr/lib64/python2.7/site-packages/keras/engine/training.py", line 232, in _check_array_lengths
    str([x.shape for x in inputs]))
ValueError: All input arrays (x) should have the same number of samples. Got array shapes: [(72, 32, 256, 1), (72, 10), (128, 1), (128, 1)]

**Comment by wenlihaoyu** [comment]
@gazibrother 这个问题已经解决，主要是batchSize太大，而测试数据集小于batchSize就会出现这个问题，请重新更新一下代码。

**Comment by huang-aoyun** [comment]
请问这个bug怎么修改，用pytorch训练时遇到的——ValueError: sampler is mutually exclusive with shuffle

**Comment by wenlihaoyu** [comment]
@huang-aoyun 哪一行代码报错？

**Comment by huang-aoyun** [comment]
@wenlihaoyu line 73，全部信息如下：
Traceback (most recent call last):
  File "crnn_main.py", line 73, in <module>
    shuffle=True, sampler=sampler)
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/data/dataloader.py", line 287, in __init__
    raise ValueError('sampler is mutually exclusive with shuffle')
ValueError: sampler is mutually exclusive with shuffle

**Comment by wenlihaoyu** [comment]
将参数 opt.random_sample改为 True,或者运作代码的train-pytorch.sh 文件改为：
cd pytorch-train
nohup python crnn_main.py --cuda --adadelta --random_sample >/tmp/crnnlog10.log 2>&1 &

**Comment by huang-aoyun** [comment]
谢谢解答，运行的时候又遇到了新问题，这是不是版本的原因呢：
Traceback (most recent call last):
  File "crnn_main.py", line 248, in <module>
    cost = trainBatch(crnn, criterion, optimizer)
  File "crnn_main.py", line 207, in trainBatch
    cost = criterion(preds, text, preds_size, length) / batch_size
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 224, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/warpctc_pytorch/__init__.py", line 60, in forward
    return _CTC()(acts, labels, act_lens, label_lens)
  File "/usr/local/lib/python2.7/dist-packages/warpctc_pytorch/__init__.py", line 26, in forward
    loss_func = warp_ctc.gpu_ctc if is_cuda else warp_ctc.cpu_ctc
AttributeError: 'module' object has no attribute 'gpu_ctc'

**Comment by wenlihaoyu** [comment]
你没有编译warp_ctc对GPU的支持，
![image](https://user-images.githubusercontent.com/7800267/34553120-c09f7864-f160-11e7-8e48-fee711a2e033.png)

**Comment by huang-aoyun** [comment]
好的，谢谢了！

**Comment by huang-aoyun** [comment]
再问一下，编译之后出现的问题：
Traceback (most recent call last):
  File "crnn_main.py", line 11, in <module>
    from warpctc_pytorch import CTCLoss
  File "/usr/local/lib/python2.7/dist-packages/warpctc_pytorch/__init__.py", line 7, in <module>
    from ._warp_ctc import lib as _lib, ffi as _ffi
ImportError: /usr/local/lib/python2.7/dist-packages/warpctc_pytorch/_warp_ctc.so: undefined symbol: state

**Comment by wenlihaoyu** [comment]
@huang-aoyun 建议用conda去配置环境

**Comment by huang-aoyun** [comment]
训练和识别都是基于keys里的词汇，貌似基于您的模型fine tune不能增加词汇数量?

**Comment by wenlihaoyu** [comment]
@huang-aoyun 只需修改模型输出层即可

**Comment by huang-aoyun** [comment]
好的，谢谢指点

**Comment by huang-aoyun** [comment]
该模型输出层怎么修改，可以大概讲一下吗？
