### ISSUE TITLE
ImportError: libopencv_reg.so.3.1: cannot enable executable stack as shared object requires: Invalid argument

### ISSUE THREAD

**Issue by wenchuanli** [chineseocr/chinese-ocr#116]
以下是错误代码，求解。。。求解！！

(chinese-ocr) root@H-09774:/usr/src/chinese-ocr-chinese-ocr-python-3.6# python demo.py
Traceback (most recent call last):
  File "demo.py", line 2, in <module>
    import model
  File "/usr/src/chinese-ocr-chinese-ocr-python-3.6/model.py", line 6, in <module>
    from ctpn.text_detect import text_detect
  File "/usr/src/chinese-ocr-chinese-ocr-python-3.6/ctpn/text_detect.py", line 1, in <module>
    from ctpn.ctpn.model import ctpn
  File "/usr/src/chinese-ocr-chinese-ocr-python-3.6/ctpn/ctpn/model.py", line 4, in <module>
    from ctpn.ctpn.other import resize_im
  File "/usr/src/chinese-ocr-chinese-ocr-python-3.6/ctpn/ctpn/other.py", line 2, in <module>
    import cv2
ImportError: libopencv_reg.so.3.1: cannot enable executable stack as shared object requires: Invalid argument

**Comment by wenlihaoyu** [comment]
opencv的问题，检查opencv是否安装正确
