### ISSUE TITLE
win7下cpu版本的安装报错，必须用Linux吗？

### ISSUE THREAD

**Issue by lusixing** [chineseocr/chinese-ocr#126]
在make-for-cpu.sh中手动执行到python setup_cpu.py build_ext --inplace出现如下错误:
running build_ext
Traceback (most recent call last):
  File "setup_cpu.py", line 125, in <module>
    cmdclass={'build_ext': custom_build_ext},
  File "d:\ProgramData\Anaconda3\envs\chinese-ocr\lib\distutils\core.py", line 1
51, in setup
    dist.run_commands()
  File "d:\ProgramData\Anaconda3\envs\chinese-ocr\lib\distutils\dist.py", line 9
53, in run_commands
    self.run_command(cmd)
  File "d:\ProgramData\Anaconda3\envs\chinese-ocr\lib\distutils\dist.py", line 9
72, in run_command
    cmd_obj.run()
  File "d:\ProgramData\Anaconda3\envs\chinese-ocr\lib\site-packages\Cython\Distu
tils\old_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "d:\ProgramData\Anaconda3\envs\chinese-ocr\lib\distutils\command\build_ex
t.py", line 340, in run
    self.build_extensions()
  File "setup_cpu.py", line 74, in build_extensions
    customize_compiler_for_nvcc(self.compiler)
  File "setup_cpu.py", line 49, in customize_compiler_for_nvcc
    default_compiler_so = self.compiler_so
AttributeError: MSVCCompiler instance has no attribute 'compiler_so'

求教博主如何解决~~

**Comment by lusixing** [comment]
在此之前setup-cpu.sh 已执行无误

**Comment by wenlihaoyu** [comment]
windows 执行keras版本的可以，pytorch可能会有一点问题。你可以试一下python3分支的代码

**Comment by DRGUO** [comment]
用python3分支的代码也遇到此问题，我也没找到解决办法，已放弃windows

**Comment by hongdajun** [comment]
我也遇到同样的问题
