### ISSUE TITLE
When I run demo.py, got error as following

### ISSUE THREAD

**Issue by jackzhang402** [chineseocr/chinese-ocr#127]
(chinese-ocr) zzl@ubuntu:~/chinese-ocr$ python demo.py 
Traceback (most recent call last):
  File "demo.py", line 2, in <module>
    import model
  File "/home/zzl/chinese-ocr/model.py", line 3, in <module>
    from ctpn.text_detect import text_detect
  File "/home/zzl/chinese-ocr/ctpn/text_detect.py", line 1, in <module>
    from ctpn.model import ctpn
  File "/home/zzl/chinese-ocr/ctpn/ctpn/model.py", line 8, in <module>
    from lib.networks.factory import get_network
  File "ctpn/lib/__init__.py", line 1, in <module>
    from . import fast_rcnn
  File "ctpn/lib/fast_rcnn/__init__.py", line 2, in <module>
    from . import train
  File "ctpn/lib/fast_rcnn/train.py", line 5, in <module>
    from ..roi_data_layer.layer import RoIDataLayer
  File "ctpn/lib/roi_data_layer/__init__.py", line 1, in <module>
    from . import roidb
  File "ctpn/lib/roi_data_layer/roidb.py", line 5, in <module>
    from lib.utils.bbox import bbox_overlaps
  File "ctpn/lib/utils/__init__.py", line 5, in <module>
    from . import cython_nms
ImportError: ctpn/lib/utils/cython_nms.so: undefined symbol: PyFPE_jbuf

**Comment by jackzhang402** [comment]
I re-setup, and it works

**Comment by larklili** [comment]
i have the same error.how to solve with it?:)thanks
