### ISSUE TITLE
关于训练crnn中文字符识别模型的数据集准备

### ISSUE THREAD

**Issue by LiangHao92** [chineseocr/chinese-ocr#13]
你好，我想自己训练一个crnn中文识别模型，但是训练集应该作为什么样的形式？我用SynthText的方法生成了拥有中文字符的图片，并保存为了h5文件。最后是需要将图片中的每行字符从原图中分割出来，并配以真是的字符作为label么。比如原图中有“我爱世界”四个字，然后需要将这四个字从原来中分割出来保存为1.jpg，然后label就是1.txt，其中内容就是“我爱世界”四个字是么？原来的rcnn模型只针对ascii字符，你的代码可以直接输入中文而不需要其他的改进么？有点疑惑，还望解答，谢谢

**Comment by hehongyu1995** [comment]
作者大大有提供ground truth生成脚本的，可以翻下issues

**Comment by wenlihaoyu** [comment]
SynthText 生成图像也可以，SynthText的效果还好一些。保存的时候就是“1.jpg，1.txt”这样的，生成的时候，你要过滤一下，比如只保留10个汉字的图片。“原来的rcnn模型只针对ascii字符”，这样没有什么关系，最后只要是unicode编码的字符其实都可以，因为最终字符都是转码了，用0、1、2、...,这样映射对应的字符，你只需维护这个关系即可。

**Comment by LiangHao92** [comment]
@wenlihaoyu 请问为什么需要只保留10个汉字的图片，是哪里作了这个限制么？之前看的crnn模型直接读取字符的ascii码来映射成0,1,2这样的label，所以需要改一下。我的意思是你的训练代码不需要改动这些是吧，直接用就行是么

**Comment by wenlihaoyu** [comment]
为了训练方便，所以才保留十个汉字，你也可以保留其他长度的，你如果训练的时候，每张图片的字符数不一样，自己还要做一些处理。训练的时候，pytorch-train/utils.py 和crnn_main.py 改了一下，把utf-8字符转为unicode就行了。你可以对比一下与原来crnn的差异。

**Comment by LiangHao92** [comment]
@wenlihaoyu 如果我选用keras来训练，是不是可以直接调用train文件夹中的train-keras.sh而不需要修改字符转码这些

**Comment by wenlihaoyu** [comment]
不需要哈，　pytorch也不需要修改，对应的代码应该修改好了的

**Comment by LiangHao92** [comment]
@wenlihaoyu 你好，我训练的时候发生了如下错误，请问是什么原因，代码对cudnn版本有要求么？我的是tensorflow1.4+cuda8.0+cudnn6.0
`Using TensorFlow backend.
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
==================================================================================================
the_input (InputLayer)          (None, 32, None, 1)  0                                            
__________________________________________________________________________________________________
conv1 (Conv2D)                  (None, 32, None, 64) 640         the_input[0][0]                  
__________________________________________________________________________________________________
pool1 (MaxPooling2D)            (None, 16, None, 64) 0           conv1[0][0]                      
__________________________________________________________________________________________________
conv2 (Conv2D)                  (None, 16, None, 128 73856       pool1[0][0]                      
__________________________________________________________________________________________________
pool2 (MaxPooling2D)            (None, 8, None, 128) 0           conv2[0][0]                      
__________________________________________________________________________________________________
conv3 (Conv2D)                  (None, 8, None, 256) 295168      pool2[0][0]                      
__________________________________________________________________________________________________
conv4 (Conv2D)                  (None, 8, None, 256) 590080      conv3[0][0]                      
__________________________________________________________________________________________________
zero_padding2d_1 (ZeroPadding2D (None, 8, None, 256) 0           conv4[0][0]                      
__________________________________________________________________________________________________
pool3 (MaxPooling2D)            (None, 4, None, 256) 0           zero_padding2d_1[0][0]           
__________________________________________________________________________________________________
conv5 (Conv2D)                  (None, 4, None, 512) 1180160     pool3[0][0]                      
__________________________________________________________________________________________________
batch_normalization_1 (BatchNor (None, 4, None, 512) 16          conv5[0][0]                      
__________________________________________________________________________________________________
conv6 (Conv2D)                  (None, 4, None, 512) 2359808     batch_normalization_1[0][0]      
__________________________________________________________________________________________________
batch_normalization_2 (BatchNor (None, 4, None, 512) 16          conv6[0][0]                      
__________________________________________________________________________________________________
zero_padding2d_2 (ZeroPadding2D (None, 4, None, 512) 0           batch_normalization_2[0][0]      
__________________________________________________________________________________________________
pool4 (MaxPooling2D)            (None, 2, None, 512) 0           zero_padding2d_2[0][0]           
__________________________________________________________________________________________________
conv7 (Conv2D)                  (None, 1, None, 512) 1049088     pool4[0][0]                      
__________________________________________________________________________________________________
permute (Permute)               (None, None, 1, 512) 0           conv7[0][0]                      
__________________________________________________________________________________________________
timedistrib (TimeDistributed)   (None, None, 512)    0           permute[0][0]                    
__________________________________________________________________________________________________
blstm1 (Bidirectional)          (None, None, 512)    1181184     timedistrib[0][0]                
__________________________________________________________________________________________________
blstm1_out (Dense)              (None, None, 256)    131328      blstm1[0][0]                     
__________________________________________________________________________________________________
blstm2 (Bidirectional)          (None, None, 512)    787968      blstm1_out[0][0]                 
__________________________________________________________________________________________________
blstm2_out (Dense)              (None, None, 5531)   2837403     blstm2[0][0]                     
__________________________________________________________________________________________________
the_labels (InputLayer)         (None, None)         0                                            
__________________________________________________________________________________________________
input_length (InputLayer)       (None, 1)            0                                            
__________________________________________________________________________________________________
label_length (InputLayer)       (None, 1)            0                                            
__________________________________________________________________________________________________
ctc (Lambda)                    (None, 1)            0           blstm2_out[0][0]                 
                                                                 the_labels[0][0]                 
                                                                 input_length[0][0]               
                                                                 label_length[0][0]               
==================================================================================================
Total params: 10,486,715
Trainable params: 10,486,699
Non-trainable params: 16
__________________________________________________________________________________________________
2017-12-13 15:06:15.173200: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2017-12-13 15:06:15.301072: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:892] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2017-12-13 15:06:15.301373: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Found device 0 with properties: 
name: GeForce GTX 1070 major: 6 minor: 1 memoryClockRate(GHz): 1.7465
pciBusID: 0000:01:00.0
totalMemory: 7.92GiB freeMemory: 7.52GiB
2017-12-13 15:06:15.392386: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:892] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2017-12-13 15:06:15.392692: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Found device 1 with properties: 
name: GeForce GTX 1070 major: 6 minor: 1 memoryClockRate(GHz): 1.7465
pciBusID: 0000:02:00.0
totalMemory: 7.92GiB freeMemory: 7.83GiB
2017-12-13 15:06:15.393065: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1045] Device peer to peer matrix
2017-12-13 15:06:15.393085: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1051] DMA: 0 1 
2017-12-13 15:06:15.393090: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1061] 0:   Y Y 
2017-12-13 15:06:15.393094: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1061] 1:   Y Y 
2017-12-13 15:06:15.393104: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1120] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: GeForce GTX 1070, pci bus id: 0000:01:00.0, compute capability: 6.1)
2017-12-13 15:06:15.393109: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1120] Creating TensorFlow device (/device:GPU:1) -> (device: 1, name: GeForce GTX 1070, pci bus id: 0000:02:00.0, compute capability: 6.1)
2017-12-13 15:06:18.932855: E tensorflow/stream_executor/cuda/cuda_dnn.cc:385] could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
2017-12-13 15:06:18.932915: E tensorflow/stream_executor/cuda/cuda_dnn.cc:352] could not destroy cudnn handle: CUDNN_STATUS_BAD_PARAM
2017-12-13 15:06:18.932931: F tensorflow/core/kernels/conv_ops.cc:667] Check failed: stream->parent()->GetConvolveAlgorithms( conv_parameters.ShouldIncludeWinogradNonfusedAlgo<T>(), &algorithms) `

**Comment by LiangHao92** [comment]
@wenlihaoyu 卸载了之前安装的keras和tensorflow，用楼主的方法安装了指定版本的环境，结果训练时报错：

`seven@seven-System-Product-Name:~/chinese-ocr/train$ sh train-keras.sh 
nohup: 忽略输入并把输出追加到"nohup.out"
*** Error in `python': double free or corruption (!prev): 0x0000000002491da0 ***
Aborted (core dumped)
`
请问这个是什么问题

**Comment by LiangHao92** [comment]
@wenlihaoyu 请问，这个问题是因为什么？你有遇到过么？是我的pytorch安装不正确？

`2017-12-13 16:23:51.215027: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2017-12-13 16:23:51.215054: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2017-12-13 16:23:51.215058: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2017-12-13 16:23:51.215062: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
2017-12-13 16:23:51.215064: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
Traceback (most recent call last):
  File "trainbatch.py", line 35, in <module>
    X,Y  =  next(iter(test_loader))
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/data/dataloader.py", line 210, in __next__
    return self._process_next_batch(batch)
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/data/dataloader.py", line 230, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
AttributeError: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/data/dataloader.py", line 42, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/seven/chinese-ocr/train/keras-train/dataset.py", line 137, in __call__
    images = [transform(image) for image in images]
  File "/home/seven/chinese-ocr/train/keras-train/dataset.py", line 81, in __call__
    img = img.resize(self.size, self.interpolation)
AttributeError: 'torch.FloatTensor' object has no attribute 'resize'`

显示没有resize这个 attribute

**Comment by wenlihaoyu** [comment]
请把运行的代码部分截图出来呢，这样不能定位到是什么问题，谢谢

**Comment by LiangHao92** [comment]
@wenlihaoyu 终端上没有什么显示

`seven@seven-System-Product-Name:~/chinese-ocr/train$ sh train-keras.sh 
nohup: 忽略输入并把输出追加到"nohup.out"
seven@seven-System-Product-Name:~/chinese-ocr/train$ 
`

**Comment by LiangHao92** [comment]
@wenlihaoyu 终端上没有错误的显示，在log里面看说是没有resize这个 attribute，谷歌了一下，说是torch有两个transform，不是很明白
`seven@seven-System-Product-Name:~/chinese-ocr/train$ sh train-keras.sh 
nohup: 忽略输入并把输出追加到"nohup.out"
seven@seven-System-Product-Name:~/chinese-ocr/train$ 
`

**Comment by LiangHao92** [comment]
@wenlihaoyu 你的torch没有出现这样的问题么？请问你的torch版本和安装方式。。。

**Comment by LiangHao92** [comment]
@wenlihaoyu 而且我选用的keras训练，为什么还是用到了torch呢

**Comment by wenlihaoyu** [comment]
我这边没有什么问题。主要用了torch的Dataset,你也可以做细微改变，不用这个，重写lmdbDataset即可。你可以把dataset 的 lmdbDatase debug一下，看是什么问题。

**Comment by LiangHao92** [comment]
@wenlihaoyu  问题报错在了resizeNormalize中的__call__里面的img = img.resize(self.size, self.interpolation)这句，感觉说没有resize这个attribute是我的torch没有配置好，，，所以想问一下，你的torch是什么版本，怎么安装的

**Comment by wenlihaoyu** [comment]
import random
import lmdb
import six
import sys
from PIL import Image
import numpy as np
from glob import glob

class lmdbDataset:

    def __init__(self, root=None, transform=None, target_transform=None):
        self.paths = glob(root)
        self.nSamples = len(self.paths)
        self.transform = transform
        self.target_transform = target_transform

    def __len__(self):
        return self.nSamples

    def __getitem__(self, index):
        assert index <= len(self), 'index range error'
        imgpath =  self.paths[index]
        txtPath =  imgpath.replace('.jpg','.txt')
        try:
             img = Image.open(imgpath).convert('L')
             with open(txtPath) as f:
                   label = f.read().strip().decode('utf-8')
        except :
                print('Corrupted image for %d' % index)
                if index>self.nSamples-1:
                    index = 0
                return self[index + 1]

        if self.transform is not None:
                img = self.transform(img)

        if self.target_transform is not None:
                label = self.target_transform(label)

        return (img, label)


这样修改也可以，直接从本地目录加载图片及label
torch版本是0.2.0_3
pip install http://download.pytorch.org/whl/cu80/torch-0.2.0.post2-cp27-cp27mu-manylinux1_x86_64.whl
或者 conda install pytorch cuda80 -c soumith

**Comment by LiangHao92** [comment]
@wenlihaoyu 这个的cudnn到底是啥版本。。。现在一直报错
“2017-12-13 19:54:50.098519: E tensorflow/stream_executor/cuda/cuda_dnn.cc:364] Loaded runtime CuDNN library: 7003 (compatibility version 7000) but source was compiled with 5110 (compatibility version 5100).  If using a binary install, upgrade your CuDNN library to match.  If building from sources, make sure the library loaded at runtime matches a compatible version specified during compile configuration.
2017-12-13 19:54:50.100706: F tensorflow/core/kernels/conv_ops.cc:672] Check failed: stream->parent()->GetConvolveAlgorithms( conv_parameters.ShouldIncludeWinogradNonfusedAlgo<T>(), &algorithms) ”
我照你的脚本，pip安装了tensorflow，报错是
`Loaded runtime CuDNN library: 7003 (compatibility version 7000) but source was compiled with 5110 (compatibility version 6021).  `
然后我又自己用源码编译了一个tensorflow，还是不行。这个7003是什么意思？

**Comment by gazibrother** [comment]
您好，生成.lmdb训练文件时，出现这样的报错，是训练材料出现问题导致的吗？
------------ 749 ------------
...................
Traceback (most recent call last):

  File "<ipython-input-52-a7db7264f40f>", line 115, in <module>
    createDataset(outputPath, imgPaths, txtLists, lexiconList=None, checkValid=True)

  File "<ipython-input-52-a7db7264f40f>", line 43, in createDataset
    env = lmdb.open(outputPath, map_size=1099511627776)

Error: E:\python\exercise\chineseocr\new1chinese-ocr-master\train\materials/lmdb/train: ���̿ռ䲻�㡣

**Comment by LiangHao92** [comment]
@wenlihaoyu 我用gpu一直报那个错误，但是一用cpu就好了，，，不知道是什么情况。方便加个微信或者qq么？方便以后交流，谢谢

**Comment by wenlihaoyu** [comment]
tensorflow选择1.3，1.4对cuda8.0支持性不是很好。CuDNN 选择5，看你上面报错提示的是，“Loaded runtime CuDNN library: 7003 (compatibility version 7000) but source was compiled with 5110 (compatibility version 6021).”，可以用：conda install tensorflow-gpu=1.3，conda会自动解决版本兼容性。

**Comment by wenlihaoyu** [comment]
@gazibrother 检查一下lmdb是否已经安装？

**Comment by wenlihaoyu** [comment]
@hehongyu1995  可以加我QQ哈，QQ: 466651950

**Comment by gazibrother** [comment]
@wenlihaoyu  哎，命途多舛，又遇到新问题了。
Traceback (most recent call last):

  File "<ipython-input-25-b49b6fd3c2ff>", line 123, in <module>
    createDataset(outputPath, imgPaths, txtLists, lexiconList=None, checkValid=True)

  File "<ipython-input-25-b49b6fd3c2ff>", line 61, in createDataset
    imageBin = f.read()

UnicodeDecodeError: 'gbk' codec can't decode byte 0xa1 in position 36: illegal multibyte sequence

**Comment by LiangHao92** [comment]
@wenlihaoyu 你好，我又来了。。。我把相关的torch等全部重装了一下，之前的问题就好了，但是遇到了新的问题：
`Traceback (most recent call last):
  File "trainbatch.py", line 33, in <module>
    model.train_on_batch( X,Y)  
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/training.py", line 1756, in train_on_batch
    check_batch_axis=True)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/training.py", line 1390, in _standardize_user_data
    _check_array_lengths(x, y, sample_weights)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/training.py", line 232, in _check_array_lengths
    str([x.shape for x in inputs]))
ValueError: All input arrays (x) should have the same number of samples. Got array shapes: [(72, 32, 256, 1), (72, 10), (128, 1), (128, 1)]
Using TensorFlow backend.`
这个是我的数据的问题么

**Comment by wenlihaoyu** [comment]
请重新更新一下代码，这个问题已经解决了

**Comment by LiangHao92** [comment]
谢谢楼主的帮助，之前没有用anaconda，安装了anacondahous后重新配置，cudnn报错的问题就解决了，就能够正常训练了

**Comment by Jeremyliu7** [comment]
@LiangHao92 请问你是怎么解决，我安装了anaconda , 使用了conda install tensorflow-gpu=1.3，重装了cudnn6.0，依然报这个错误：Loaded runtime CuDNN library: 7003 (compatibility version 7000) but source was compiled with 5110 (compatibility version 6021).

**Comment by LiangHao92** [comment]
新建个环境：
`conda create -n crnn python=X.X（2.7、3.6等）`
crnn是环境名字，可随意更改
然后source activate crnn  启动环境，再照着楼主的install步骤就行了。
为了方便管理，我直接把代码扔进了anaconda文件夹下的envs/crnn下

**Comment by Jeremyliu7** [comment]
"为了训练方便，所以才保留十个汉字，你也可以保留其他长度的，你如果训练的时候，每张图片的字符数不一样，自己还要做一些处理。"你好，@wenlihaoyu  请问不同长度的字符一起训练该如何处理呢，我这边case是一个ImageLine上从2到24个字的都有。

**Comment by wenlihaoyu** [comment]
@Jeremyliu7 保证每一个batch 的字符长度一致即可

**Comment by LiangHao92** [comment]
@Jeremyliu7 你好，请问对于不定长度字符的数据集训练，最后你处理成功了么

**Comment by gentleduo** [comment]
我想问下在keras-train里的train.py文件里的 genarator生成里面 Length = int(imgW/4)-1这句话是啥意思？
为啥要对input_length做这样的操作，我比较菜 望大神指点 谢谢
