### ISSUE TITLE
ValueError: sampler is mutually exclusive with shuffle

### ISSUE THREAD

**Issue by mzniu** [chineseocr/chinese-ocr#136]
各位大神，我在训练pytorch的时候报了下面的错，有人知道怎么回事儿么？多谢。
Traceback (most recent call last):
  File "crnn_main.py", line 75, in <module>
    collate_fn=dataset.alignCollate(imgH=opt.imgH, imgW=opt.imgW, keep_ratio=opt.keep_ratio))
  File "/etc/anaconda2/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 296, in __init__
    raise ValueError('sampler is mutually exclusive with shuffle')
ValueError: sampler is mutually exclusive with shuffle

**Comment by zxczhkzxc** [comment]
在 python crnn_main.py 后加上 --random_sample 就没问题了
