### ISSUE TITLE
from . import config ERROR: cannot import name config

### ISSUE THREAD

**Issue by jchan698** [chineseocr/chinese-ocr#140]
你好, 我已经运行 setup.sh 和 make.sh 可是在 chinese-ocr-master folder 时候 import model 的时候出如下问题:
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File  "model.py", line 3, in <module>
   from ctpn.text_detect import text_detect
File "ctpn/__init__.py", line 7, in <module>
   from lib import fast_rcnn
File "ctpn/lib/__init__.py", line 1, in <,module>
   from . import config
ImportError: cannot import name config

好像有很多类似的问题,大家有没有建议能解决这些ImportError, 谢谢!

**Comment by wenlihaoyu** [comment]
python3 还是python2?

**Comment by jchan698** [comment]
python 2 需要动 几个 folder 吗还是运行setup.sh 和 make.sh 就够了？

**Comment by wenlihaoyu** [comment]
master  就是python2环境
