### ISSUE TITLE
ValueError: Variable conv1_1/weights already exists

### ISSUE THREAD

**Issue by dizhou123** [chineseocr/chinese-ocr#162]
大神能帮我看看这个报错吗？

Traceback (most recent call last):
  File "/Users/ookishi/Documents/dizhou/chinese-ocr-master/demo.py", line 2, in <module>
    import model
  File "/Users/ookishi/Documents/dizhou/chinese-ocr-master/model.py", line 12, in <module>
    from ctpn.ctpn.model import ctpn
  File "/Users/ookishi/Documents/dizhou/chinese-ocr-master/ctpn/ctpn/model.py", line 27, in <module>
    sess,saver,net = load_tf_model()
  File "/Users/ookishi/Documents/dizhou/chinese-ocr-master/ctpn/ctpn/model.py", line 19, in load_tf_model
    net = get_network("VGGnet_test")
  File "/Users/ookishi/Documents/dizhou/chinese-ocr-master/ctpn/lib/networks/factory.py", line 8, in get_network
    return VGGnet_test()
  File "/Users/ookishi/Documents/dizhou/chinese-ocr-master/ctpn/lib/networks/VGGnet_test.py", line 14, in __init__
    self.setup()
  File "/Users/ookishi/Documents/dizhou/chinese-ocr-master/ctpn/lib/networks/VGGnet_test.py", line 21, in setup
    .conv(3, 3, 64, 1, 1, name='conv1_1')
  File "/Users/ookishi/Documents/dizhou/chinese-ocr-master/ctpn/lib/networks/network.py", line 23, in layer_decorated
    layer_output = op(self, layer_input, *args, **kwargs)
  File "/Users/ookishi/Documents/dizhou/chinese-ocr-master/ctpn/lib/networks/network.py", line 173, in conv
    regularizer=self.l2_regularizer(cfg.TRAIN.WEIGHT_DECAY))
  File "/Users/ookishi/Documents/dizhou/chinese-ocr-master/ctpn/lib/networks/network.py", line 84, in make_var
    return tf.get_variable(name, shape, initializer=initializer, trainable=trainable, regularizer=regularizer)
  File "/Users/ookishi/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/variable_scope.py", line 1262, in get_variable
    constraint=constraint)
  File "/Users/ookishi/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/variable_scope.py", line 1097, in get_variable
    constraint=constraint)
  File "/Users/ookishi/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/variable_scope.py", line 435, in get_variable
    constraint=constraint)
  File "/Users/ookishi/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/variable_scope.py", line 404, in _true_getter
    use_resource=use_resource, constraint=constraint)
  File "/Users/ookishi/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/variable_scope.py", line 743, in _get_single_variable
    name, "".join(traceback.format_list(tb))))
ValueError: Variable conv1_1/weights already exists, disallowed. Did you mean to set reuse=True or reuse=tf.AUTO_REUSE in VarScope? Originally defined at:

  File "/Users/ookishi/Documents/dizhou/chinese-ocr-master/ctpn/lib/networks/network.py", line 84, in make_var
    return tf.get_variable(name, shape, initializer=initializer, trainable=trainable, regularizer=regularizer)
  File "/Users/ookishi/Documents/dizhou/chinese-ocr-master/ctpn/lib/networks/network.py", line 173, in conv
    regularizer=self.l2_regularizer(cfg.TRAIN.WEIGHT_DECAY))
  File "/Users/ookishi/Documents/dizhou/chinese-ocr-master/ctpn/lib/networks/network.py", line 23, in layer_decorated
    layer_output = op(self, layer_input, *args, **kwargs)

**Comment by wenlihaoyu** [comment]
tensorflow 可以是1.3或者1.4，其它版本，可能会有一些问题

**Comment by dizhou123** [comment]
@wenlihaoyu 谢谢，已经解决了
