### ISSUE TITLE
请问运行GPU版本时报如下错，是什么问题？

### ISSUE THREAD

**Issue by wgq126** [chineseocr/chinese-ocr#177]
![2018-04-18 12-38-46](https://user-images.githubusercontent.com/35617745/38912030-a50aa91a-4305-11e8-9a2c-d16da768f3fa.png)

**Comment by wgq126** [comment]
Traceback (most recent call last):
  File "demo.py", line 13, in <module>
    result,img,angle = model.model(img,model='keras')
  File "/home/chinese-ocr-master/model.py", line 94, in model
    text_recs,tmp,img = text_detect(img)
  File "/home/chinese-ocr-master/ctpn/text_detect.py", line 6, in text_detect
    scores, boxes,img = ctpn(img)
  File "/home/chinese-ocr-master/ctpn/ctpn/model.py", line 34, in ctpn
    scores, boxes = test_ctpn(sess, net, img)
  File "ctpn/lib/fast_rcnn/test.py", line 51, in test_ctpn
    rois = sess.run([net.get_output('rois')[0]],feed_dict=feed_dict)
  File "/opt/miniconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 895, in run
    run_metadata_ptr)
  File "/opt/miniconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1124, in _run
    feed_dict_tensor, options, run_metadata)
  File "/opt/miniconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1321, in _do_run
    options, run_metadata)
  File "/opt/miniconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1340, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InternalError: Blas GEMM launch failed : a.shape=(56, 640), b.shape=(640, 512), m=56, n=512, k=640
	 [[Node: lstm_o/bidirectional_rnn/fw/fw/while/fw/lstm_cell/lstm_cell/lstm_cell/MatMul = MatMul[T=DT_FLOAT, transpose_a=false, transpose_b=false, _device="/job:localhost/replica:0/task:0/gpu:0"](lstm_o/bidirectional_rnn/fw/fw/while/fw/lstm_cell/lstm_cell/lstm_cell/concat, lstm_o/bidirectional_rnn/fw/fw/while/fw/lstm_cell/lstm_cell/lstm_cell/MatMul/Enter)]]
	 [[Node: Reshape_2/_79 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_496_Reshape_2", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]

Caused by op u'lstm_o/bidirectional_rnn/fw/fw/while/fw/lstm_cell/lstm_cell/lstm_cell/MatMul', defined at:
  File "demo.py", line 2, in <module>
    import model
  File "/home/chinese-ocr-master/model.py", line 3, in <module>
    from ctpn.text_detect import text_detect
  File "/home/chinese-ocr-master/ctpn/text_detect.py", line 1, in <module>
    from ctpn.model import ctpn
  File "/home/chinese-ocr-master/ctpn/ctpn/model.py", line 26, in <module>
    sess,saver,net = load_tf_model()
  File "/home/chinese-ocr-master/ctpn/ctpn/model.py", line 18, in load_tf_model
    net = get_network("VGGnet_test")
  File "ctpn/lib/networks/factory.py", line 8, in get_network
    return VGGnet_test()
  File "ctpn/lib/networks/VGGnet_test.py", line 14, in __init__
    self.setup()
  File "ctpn/lib/networks/VGGnet_test.py", line 41, in setup
    (self.feed('rpn_conv/3x3').Bilstm(512, 128, 512, name='lstm_o'))
  File "ctpn/lib/networks/network.py", line 23, in layer_decorated
    layer_output = op(self, layer_input, *args, **kwargs)
  File "ctpn/lib/networks/network.py", line 102, in Bilstm
    lstm_out, last_state = tf.nn.bidirectional_dynamic_rnn(lstm_fw_cell,lstm_bw_cell, img, dtype=tf.float32)
  File "/opt/miniconda2/lib/python2.7/site-packages/tensorflow/python/ops/rnn.py", line 405, in bidirectional_dynamic_rnn
    time_major=time_major, scope=fw_scope)
  File "/opt/miniconda2/lib/python2.7/site-packages/tensorflow/python/ops/rnn.py", line 598, in dynamic_rnn
    dtype=dtype)
  File "/opt/miniconda2/lib/python2.7/site-packages/tensorflow/python/ops/rnn.py", line 761, in _dynamic_rnn_loop
    swap_memory=swap_memory)
  File "/opt/miniconda2/lib/python2.7/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2775, in while_loop
    result = context.BuildLoop(cond, body, loop_vars, shape_invariants)
  File "/opt/miniconda2/lib/python2.7/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2604, in BuildLoop
    pred, body, original_loop_vars, loop_vars, shape_invariants)
  File "/opt/miniconda2/lib/python2.7/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2554, in _BuildLoop
    body_result = body(*packed_vars_for_body)
  File "/opt/miniconda2/lib/python2.7/site-packages/tensorflow/python/ops/rnn.py", line 746, in _time_step
    (output, new_state) = call_cell()
  File "/opt/miniconda2/lib/python2.7/site-packages/tensorflow/python/ops/rnn.py", line 732, in <lambda>
    call_cell = lambda: cell(input_t, state)
  File "/opt/miniconda2/lib/python2.7/site-packages/tensorflow/python/ops/rnn_cell_impl.py", line 180, in __call__
    return super(RNNCell, self).__call__(inputs, state)
  File "/opt/miniconda2/lib/python2.7/site-packages/tensorflow/python/layers/base.py", line 450, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "/opt/miniconda2/lib/python2.7/site-packages/tensorflow/python/ops/rnn_cell_impl.py", line 564, in call
    lstm_matrix = _linear([inputs, m_prev], 4 * self._num_units, bias=True)
  File "/opt/miniconda2/lib/python2.7/site-packages/tensorflow/python/ops/rnn_cell_impl.py", line 1043, in _linear
    res = math_ops.matmul(array_ops.concat(args, 1), weights)
  File "/opt/miniconda2/lib/python2.7/site-packages/tensorflow/python/ops/math_ops.py", line 1844, in matmul
    a, b, transpose_a=transpose_a, transpose_b=transpose_b, name=name)
  File "/opt/miniconda2/lib/python2.7/site-packages/tensorflow/python/ops/gen_math_ops.py", line 1289, in _mat_mul
    transpose_b=transpose_b, name=name)
  File "/opt/miniconda2/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "/opt/miniconda2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2630, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/opt/miniconda2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1204, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InternalError (see above for traceback): Blas GEMM launch failed : a.shape=(56, 640), b.shape=(640, 512), m=56, n=512, k=640
	 [[Node: lstm_o/bidirectional_rnn/fw/fw/while/fw/lstm_cell/lstm_cell/lstm_cell/MatMul = MatMul[T=DT_FLOAT, transpose_a=false, transpose_b=false, _device="/job:localhost/replica:0/task:0/gpu:0"](lstm_o/bidirectional_rnn/fw/fw/while/fw/lstm_cell/lstm_cell/lstm_cell/concat, lstm_o/bidirectional_rnn/fw/fw/while/fw/lstm_cell/lstm_cell/lstm_cell/MatMul/Enter)]]
	 [[Node: Reshape_2/_79 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_496_Reshape_2", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]

请问是咋回事呢？版主您知道吗？
