### ISSUE TITLE
How to run this program?

### ISSUE THREAD

**Issue by pustar** [chineseocr/chinese-ocr#2]
Very thankful for your nice share! Can you write some instructions for running this program? I have tried many times to run it, but failed!

**Comment by wenlihaoyu** [comment]
First，you should run " sh setup.sh" to setup and build the environment，keras=2.0.8 tensorflow==1.3 tensorflow-gpu=1.3, test on ubuntu14/16.
Then,open the demo.ipynb with notebook,if run the demo is error when "import",Please install the missing module.

**Comment by wenlihaoyu** [comment]
or run python demo.py

**Comment by gazibrother** [comment]
您好，运行demo时，我把model切换到crnn，得到的结果是乱码，请问该怎样调整？  结果如下：

“洒?锚U晒洒涕朐肋励棉札雀否冶0蛳昵岘电U咿朋哚漪蔽劭兀冶砾跎础嫦厥亲虑.砣悉娆靳琢砾忌砌蓬碰冶溱鄱邴泌沁U韶酌沁渊肮胱庇0皈嬷狍礁抽U栗莱枭
嵘?谦漱驮鸵耽苡凹汤D盯邡煦巾冶柒螈昵叽臾喉沁札屯酣虑聪荫币啉蜥螈遨邀’
喹?蛛膝嚓郦啄贬脲哚咪漱’
醛既娆硪睨砣O3巯黍誓奉娆砀晰肠厩柒螂毗蜒毗肋晚嵘醚鸵撕鹜贬
。
喋?舫|忌抱5鄂粟栾果猷骰戊砀郡弼码砾渐啉邀漱潋1蹶5|107.16C56
“

**Comment by wenlihaoyu** [comment]
请把你详细的代码粘贴处理，不然我也不知道是什么问题，谢谢！

**Comment by bleehome** [comment]
你好，执行   
python demo.py 之后，出现下面的错误，是漏了什么步骤吗？谢谢了

`(chinese-ocr) [root@localhost chinese-ocr]# python demo.py     
                                                                                                                                                                             
2017-12-20 16:09:24.894292: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.

2017-12-20 16:09:24.894328: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2017-12-20 16:09:24.894335: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.

2017-12-20 16:09:24.894341: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.

Tensor("Placeholder:0", shape=(?, ?, ?, 3), dtype=float32)

Tensor("conv5_3/conv5_3:0", shape=(?, ?, ?, 512), dtype=float32)

Tensor("rpn_conv/3x3/rpn_conv/3x3:0", shape=(?, ?, ?, 512), dtype=float32)

/opt/anaconda2/envs/chinese-ocr/lib/python2.7/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.

  from ._conv import register_converters as _register_converters

Tensor("lstm_o/Reshape_2:0", shape=(?, ?, ?, 512), dtype=float32)

Tensor("lstm_o/Reshape_2:0", shape=(?, ?, ?, 512), dtype=float32)

Tensor("rpn_cls_score/Reshape_1:0", shape=(?, ?, ?, 20), dtype=float32)

Tensor("rpn_cls_prob:0", shape=(?, ?, ?, ?), dtype=float32)

Tensor("Reshape_2:0", shape=(?, ?, ?, 20), dtype=float32)

Tensor("rpn_bbox_pred/Reshape_1:0", shape=(?, ?, ?, 40), dtype=float32)

Tensor("Placeholder_1:0", shape=(?, 3), dtype=float32)

Using TensorFlow backend.

Traceback (most recent call last):

  File "demo.py", line 2, in <module>

    import model

  File "/root/chinese-ocr/model.py", line 5, in <module>

    from angle.predict import predict as angle_detect##文字方向检测

  File "/root/chinese-ocr/angle/predict.py", line 25, in <module>

    model = load()
  File "/root/chinese-ocr/angle/predict.py", line 21, in load
    model.load_weights('./angle/modelAngle.h5')
  File "/opt/anaconda2/envs/chinese-ocr/lib/python2.7/site-packages/keras/engine/topology.py", line 2613, in load_weights
    f = h5py.File(filepath, mode='r')

  File "/opt/anaconda2/envs/chinese-ocr/lib/python2.7/site-packages/h5py/_hl/files.py", line 269, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)

  File "/opt/anaconda2/envs/chinese-ocr/lib/python2.7/site-packages/h5py/_hl/files.py", line 99, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)

  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper

  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper

  File "h5py/h5f.pyx", line 78, in h5py.h5f.open

IOError: Unable to open file (unable to open file: name = './angle/modelAngle.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
`

**Comment by wenlihaoyu** [comment]
@bleehome ./angle/modelAngle.h5 文件没有下载

**Comment by daiw10** [comment]
@gazibrother 你好，请问你后来有解决这个问题么，我也遇到了。。不是编码问题

**Comment by wxh928408225** [comment]
@bleehome you can download the `./angle/modelAngle.h5 `   from  https://pan.baidu.com/s/1pM2ha5P or [Google Drive Address](https://drive.google.com/file/d/1Pn_Jj_EFXUSuWgZZPCGQZcgkgj33r7Ml/view?usp=sharing)
