### ISSUE TITLE
keras-train训练错误：ValueError: Error when checking input: expected the_labels to have 2 dimensions, but got array with shape ()

### ISSUE THREAD

**Issue by favpdf** [chineseocr/chinese-ocr#21]
2017-12-25 16:17:16.194928: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
Epoch 1/10
3/4 [=====================>........] - ETA: 1s - loss: 228.5950Traceback (most recent call last):
  File "train.py", line 85, in <module>
    validation_steps = 1024)
  File "/usr/local/lib/python2.7/dist-packages/keras/legacy/interfaces.py", line 87, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/training.py", line 2064, in fit_generator
    use_multiprocessing=use_multiprocessing)
  File "/usr/local/lib/python2.7/dist-packages/keras/legacy/interfaces.py", line 87, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/training.py", line 2176, in evaluate_generator
    outs = self.test_on_batch(x, y, sample_weight=sample_weight)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/training.py", line 1798, in test_on_batch
    check_batch_axis=True)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/training.py", line 1378, in _standardize_user_data
    exception_prefix='input')
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/training.py", line 132, in _standardize_input_data
    str(array.shape))
ValueError: Error when checking input: expected the_labels to have 2 dimensions, but got array with shape ()

以上是错误的堆栈，请帮忙看下是什么原因，谢谢！

**Comment by favpdf** [comment]
错误发生在计算val_loss阶段，训练阶段好像没有问题。

**Comment by favpdf** [comment]
如果把测试数据用训练数据来代替就没问题了，validation_data = gen(test_loader), 改成 validation_data = gen(train_loader), 该错误可能的原因是：默认的测试数据有问题，请作者帮忙确认一下，谢谢！

**Comment by LiangHao92** [comment]
同遇到这个问题，用trainbatch.py这个训练就没有问题

**Comment by huang-aoyun** [comment]
减小batchsize可以解决，估计是显存太小了

**Comment by favpdf** [comment]
可能跟batchsize没多大关系，我贴的log里头batchsize是4，很小了。

**Comment by wenlihaoyu** [comment]
@favpdf 这个错误已经更正了，更新train.py  文件即可

**Comment by favpdf** [comment]
谢谢更新！
