### ISSUE TITLE
ImportError: dlopen: cannot load any more object with static TLS

### ISSUE THREAD

**Issue by quanh** [chineseocr/chinese-ocr#24]
I installed `pytorch 0.1.12` with pip , build` etc` and `pytorch blinding` , build `ctpn/ctpn/lib` with  `setup_cpu.py` . 

I run `python demo.py` , and got error:

`2017-12-26 17:19:13.932867: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2017-12-26 17:19:13.932890: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2017-12-26 17:19:13.932898: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2017-12-26 17:19:13.932904: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
2017-12-26 17:19:13.932909: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
Tensor("Placeholder:0", shape=(?, ?, ?, 3), dtype=float32)
Tensor("conv5_3/conv5_3:0", shape=(?, ?, ?, 512), dtype=float32)
Tensor("rpn_conv/3x3/rpn_conv/3x3:0", shape=(?, ?, ?, 512), dtype=float32)
WARNING:tensorflow:<tensorflow.python.ops.rnn_cell_impl.BasicLSTMCell object at 0x7f9fea164310>: Using a concatenated state is slower and will soon be deprecated.  Use state_is_tuple=True.
Tensor("lstm_o/Reshape:0", shape=(?, ?, ?, 128), dtype=float32)
Tensor("lstm_o/Reshape:0", shape=(?, ?, ?, 128), dtype=float32)
Tensor("rpn_cls_score/Reshape:0", shape=(?, ?, ?, 20), dtype=float32)
Tensor("rpn_cls_prob:0", shape=(?, ?, ?, ?), dtype=float32)
Tensor("Reshape_5:0", shape=(?, ?, ?, 20), dtype=float32)
Tensor("rpn_bbox_pred/Reshape:0", shape=(?, ?, ?, 40), dtype=float32)
Tensor("Placeholder_1:0", shape=(?, 3), dtype=float32)
Using TensorFlow backend.
/usr/local/lib/python2.7/dist-packages/keras/models.py:251: UserWarning: No training configuration found in save file: the model was *not* compiled. Compile it manually.
  warnings.warn('No training configuration found in save file: '
Traceback (most recent call last):
  File "demo.py", line 2, in <module>
    import model
  File "/opt/Srcs/chinese-ocr/model.py", line 5, in <module>
    from crnn.crnn import crnnOcr
  File "/opt/Srcs/chinese-ocr/crnn/crnn.py", line 6, in <module>
    import torch
  File "/usr/local/lib/python2.7/dist-packages/torch/__init__.py", line 53, in <module>
    from torch._C import *
ImportError: dlopen: cannot load any more object with static TLS`

It seems that , the error caused by. pytorch ,  I reinstalled the pytorch by source , but did not resolve .

I run `rcnn` and   `cptn`   separate, work well .  I tried many times , have no idea now . Thanks for reading , hope  for someone help me.

**Comment by wenlihaoyu** [comment]
you can comment the model.py line 5 : "# from crnn.crnn import crnnOcr" , whether is error?

**Comment by quanh** [comment]
@wenlihaoyu  It works , thanks.

**Comment by zttjava** [comment]
I have the same problem,how did you solve it?

**Comment by shuihuadx** [comment]
I got same error.
But i want to run demo.py with torch,so i can't comment this [line](https://github.com/chineseocr/chinese-ocr/blob/master/model.py#L6)

this is my error:

>Traceback (most recent call last):
  File "demo.py", line 3, in <module>
    import model
  File "/home/gamepp/DX/chinese-ocr/model.py", line 9, in <module>
    from crnn.crnn import crnnOcr
  File "/home/gamepp/DX/chinese-ocr/crnn/crnn.py", line 6, in <module>
    import torch
  File "/root/miniconda2/lib/python2.7/site-packages/torch/__init__.py", line 53, in <module>
    from torch._C import *
ImportError: dlopen: cannot load any more object with static TLS


Finally,I find the [solution](https://github.com/pytorch/pytorch/issues/2083#issuecomment-349811601).

Just add `import torch` into chinese-ocr/model.py,it is work!

**Comment by LCorleone** [comment]
@shuihuadx hi，i add import torch in model.py , but it did not work!
