### ISSUE TITLE
run demo.py error

### ISSUE THREAD

**Issue by fiser321** [chineseocr/chinese-ocr#27]
我的环境是python3, 只修改了print 为print(), 遍历字典时的iteritems() 修改为items()，但出现报错

(env-new) root@op-System-Product-Name:/home/github/tf-image/ocr/chinese-ocr#  python demo.py 
Traceback (most recent call last):
  File "demo.py", line 2, in <module>
    import model
  File "/home/github/tf-image/ocr/chinese-ocr/model.py", line 3, in <module>
    from ctpn.text_detect import text_detect
  File "/home/github/tf-image/ocr/chinese-ocr/ctpn/text_detect.py", line 1, in <module>
    from ctpn.model import ctpn
ImportError: No module named 'ctpn.model'
(env-new) root@op-System-Product-Name:/home/github/tf-image/ocr/chinese-ocr#

**Comment by wenlihaoyu** [comment]
可能是python3 import的问题，你在ctpn/text_detect.py 文件顶部加入如下：

**Comment by LauryMiao** [comment]
加了，问题同样存在。
import sys
sys.path.append('ctpn')

然后试了py2，并参考：https://github.com/chineseocr/chinese-ocr/issues/3 ， 跑通。
