### ISSUE TITLE
how to modify the code to run it on my computer?

### ISSUE THREAD

**Issue by hsongNathanial** [chineseocr/chinese-ocr#3]
I think I have downloaded all the packet which we need, but I still fail to run the code. Maybe because of the path? where should I modify to run it on my computer?

This is my error

>>> import model
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "model.py", line 3, in <module>
    from ctpn.text_detect import text_detect
  File "ctpn/text_detect.py", line 1, in <module>
    from ctpn.model import ctpn
  File "ctpn/ctpn/model.py", line 8, in <module>
    from lib.networks.factory import get_network
  File "ctpn/lib/__init__.py", line 1, in <module>
    import fast_rcnn
  File "ctpn/lib/fast_rcnn/__init__.py", line 8, in <module>
    from . import config
ImportError: cannot import name config

Best regards

**Comment by hsongNathanial** [comment]
and sometimes I will meet this error
>>> import model
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "model.py", line 3, in <module>
    from ctpn.text_detect import text_detect
  File "ctpn/text_detect.py", line 1, in <module>
    from ctpn.model import ctpn
  File "ctpn/ctpn/model.py", line 8, in <module>
    from lib.networks.factory import get_network
  File "ctpn/lib/__init__.py", line 1, in <module>
    import fast_rcnn
  File "ctpn/lib/fast_rcnn/__init__.py", line 9, in <module>
    from . import train
  File "ctpn/lib/fast_rcnn/train.py", line 6, in <module>
    from ..roi_data_layer.layer import RoIDataLayer
  File "ctpn/lib/roi_data_layer/__init__.py", line 7, in <module>
    import roidb
  File "ctpn/lib/roi_data_layer/roidb.py", line 19, in <module>
    from ..utils.cython_bbox import bbox_overlaps
  File "ctpn/lib/utils/__init__.py", line 7, in <module>
    from . import cython_nms
ImportError: cannot import name cython_nms

**Comment by wenlihaoyu** [comment]
when run the demo.py, you should run "sh setup.sh" or :
pip install easydict -i https://pypi.tuna.tsinghua.edu.cn/simple/ 
pip install keras==2.0.8 tensorflow==1.3 tensorflow-gpu==1.3 -i https://pypi.tuna.tsinghua.edu.cn/simple/ 
pip install Cython opencv-python -i https://pypi.tuna.tsinghua.edu.cn/simple/ 
pip install matplotlib -i https://pypi.tuna.tsinghua.edu.cn/simple/ 
cd ./ctpn/lib
python setup.py build

**Comment by hsongNathanial** [comment]
执行过之后不管用啊，始终出现这个问题
ImportError: cannot import name cython_nms

**Comment by hsongNathanial** [comment]
单独把每一句拿出来执行还是不行

**Comment by huguyuehuhu** [comment]
Hi,  @wenlihaoyu   I had the same problem with @hsongNathanial . I  even made a virtual environment for   this project through anaconda ,and   I already run the commands"cd ./ctpn/lib
python setup.py build", so the  *.so is already created, 
![a](https://user-images.githubusercontent.com/25881545/32723753-9b4ac35a-c8a9-11e7-8ce3-dec2ef24e1d3.jpg)
but I still can not import cython_nms and cython_bbox through your code " from  . import cython_nms
from . import cython_bbox"

**Comment by huguyuehuhu** [comment]
Hi, @wenlihaoyu I had the same problem with @hsongNathanial . I even made a virtual environment for this project through anaconda ,and I already run the commands"cd ./ctpn/lib
python setup.py build", so the *.so files is already created,
![b](https://user-images.githubusercontent.com/25881545/32723836-e41f2332-c8a9-11e7-99ac-2769e2d50531.jpg)
but I still can not import cython_nms and cython_bbox through your code " from . import cython_nms
from . import cython_bbox". Can you do me some help? Thanks

**Comment by mtobeiyf** [comment]
**Solution:**
In the file `./ctpn/lib/setup.py`, comment line 55 and line 127 to 143.
```
# CUDA = locate_cuda()

    # Extension('nms.gpu_nms',
    #     ['nms/nms_kernel.cu', 'nms/gpu_nms.pyx'],
    #     library_dirs=[CUDA['lib64']],
    #     libraries=['cudart'],
    #     language='c++',
    #     runtime_library_dirs=[CUDA['lib64']],
    #     # this syntax is specific to this build system
    #     # we're only going to use certain compiler args with nvcc and not with gcc
    #     # the implementation of this trick is in customize_compiler() below
    #     extra_compile_args={'gcc': ["-Wno-unused-function"],
    #                         'nvcc': ['-arch=sm_35',
    #                                  '--ptxas-options=-v',
    #                                  '-c',
    #                                  '--compiler-options',
    #                                  "'-fPIC'"]},
    #     include_dirs = [numpy_include, CUDA['include']]
    # ),
```
run command `cd ./ctpn/lib & python setup.py build` to build the libraries.

**copy** two .so files under dir `./ctpn/lib/build/lib.linux-x86_64-2.7/utils` to `./ctpn/lib/utils/`

then, cython_nms would be successfully imported

**Comment by huguyuehuhu** [comment]
@mtobeiyf  Thanks you very much for sharing your solution, I also found out a alternative way in my machine.  Solution: 1.run command cd ./ctpn/lib & python setup.py build 2.  Then run the  command      make  -j8 ; After the  command, it  will create  the soft link to ./ctpn/lib/utils/ .  I guess that due to the" Makefile ” in path, have not been run.

**Comment by huguyuehuhu** [comment]
@mtobeiyf Thanks you very much for sharing your solution, I also found out a alternative way in my machine. Solution: 1.run command cd ./ctpn/lib & python setup.py build 2. Then run the command make -j8 ; After the command, it will create the soft link to ./ctpn/lib/utils/ . I guess that due to the" Makefile ” in path, have not been run.

**Comment by huguyuehuhu** [comment]
Thanks you very much for sharing your solution, I also found out a alternative way in my machine. Solution: 1.run command cd ./ctpn/lib & python setup.py build 2. Then run the command make -j8 ; After the command, it will create the soft link to ./ctpn/lib/utils/ . I guess that due to the" Makefile ” have not been run.

**Comment by JavamanJosen** [comment]
setup.sh中的    tensorflow-gpu==1.3 -i https://pypi.tuna.tsinghua.edu.cn/simple/  找不到1.3版本，求解决

**Comment by wenlihaoyu** [comment]
@JavamanJosen 你用的什么系统，windows系统我没有测试过，linux系统应该没有什么问题
