### ISSUE TITLE
运行setup.py 出现的问题

### ISSUE THREAD

**Issue by frankzhuo** [chineseocr/chinese-ocr#35]
Traceback (most recent call last):
  File "setup.py", line 55, in <module>
    CUDA = locate_cuda()
  File "setup.py", line 43, in locate_cuda
    raise EnvironmentError('The nvcc binary could not be '
EnvironmentError: The nvcc binary could not be located in your $PATH. Either add it to your path, or set $CUDAHOME

**Comment by wenlihaoyu** [comment]
查看你系统GPU驱动是否安装正确，如果没有GPU，安装CPU版本即可。

**Comment by frankzhuo** [comment]
python setup.py build   
![image](https://user-images.githubusercontent.com/8016063/34513875-6c6d60d2-f0a5-11e7-8e4d-d170d5262100.png)

**Comment by frankzhuo** [comment]
build 总通不过去，真的弄蒙了，博主可以传一份吗，麻烦你了

**Comment by wenlihaoyu** [comment]
推荐用conda 去配置python环境，安装原生态的python可能有一些问题，不然有些包需要自己去手动编译。配置好后，先试一下能否编译通过CPU版本的　text-detect:https://github.com/chineseocr/new-text-detection-ctpn.git

**Comment by frankzhuo** [comment]
File "/home/frank/桌面/chineseOcr/ctpn/lib/roi_data_layer/roidb.py", line 19, in <module>
    from ..utils.cython_bbox import bbox_overlaps
  File "/home/frank/桌面/chineseOcr/ctpn/lib/utils/__init__.py", line 7, in <module>
    from . import cython_nms
ImportError: cannot import name cython_nms

实在是弄晕了，麻烦博主哥哥了

**Comment by wenlihaoyu** [comment]
通过这个链接下载python进行安装，这些问题应该就没有了。https://repo.continuum.io/archive/Anaconda2-5.0.1-Linux-x86_64.sh

**Comment by frankzhuo** [comment]
这个安过的  File "/home/frank/桌面/chineseOcr/ocr/model.py", line 2, in <module>
    from keras.layers import Input,Conv2D,MaxPooling2D,ZeroPadding2D
ImportError: No module named keras.layers
不好意思问了。。。。。我给点给博主gg star

**Comment by wenlihaoyu** [comment]
@frankzhuo "ImportError: No module named keras.layers",你keras都没有安装的嘛
