### ISSUE TITLE
CPU版本问题

### ISSUE THREAD

**Issue by moondaiy** [chineseocr/chinese-ocr#39]
楼主程序很棒，但是我目前环境如下。
ubuton：1604  无GPU pytorch 和kerras tensorflow 均按照要求进行配置，但是使用的是python3.6版本
更改程序将一些不符合3.6版本的python语句进行更改。

但是在执行python demo.py 的时候  出现如下错误
(Python3_6) root@tcloud-bbsq-app30:/home/lxw/python_prj/chinese-ocr-master# python demo.py 
2018-01-04 18:13:10.432936: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2018-01-04 18:13:10.432964: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2018-01-04 18:13:10.432970: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2018-01-04 18:13:10.432975: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
2018-01-04 18:13:10.432979: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
Tensor("Placeholder:0", shape=(?, ?, ?, 3), dtype=float32)
Tensor("conv5_3/conv5_3:0", shape=(?, ?, ?, 512), dtype=float32)
Tensor("rpn_conv/3x3/rpn_conv/3x3:0", shape=(?, ?, ?, 512), dtype=float32)
WARNING:tensorflow:<tensorflow.python.ops.rnn_cell_impl.BasicLSTMCell object at 0x7f42a719f320>: Using a concatenated state is slower and will soon be deprecated.  Use state_is_tuple=True.
Tensor("lstm_o/Reshape:0", shape=(?, ?, ?, 128), dtype=float32)
Tensor("lstm_o/Reshape:0", shape=(?, ?, ?, 128), dtype=float32)
Tensor("rpn_cls_score/Reshape:0", shape=(?, ?, ?, 20), dtype=float32)
Tensor("rpn_cls_prob:0", shape=(?, ?, ?, ?), dtype=float32)
Tensor("Reshape_5:0", shape=(?, ?, ?, 20), dtype=float32)
Tensor("rpn_bbox_pred/Reshape:0", shape=(?, ?, ?, 40), dtype=float32)
Tensor("Placeholder_1:0", shape=(?, 3), dtype=float32)
Using TensorFlow backend.
/root/anaconda3/envs/Python3_6/lib/python3.6/site-packages/keras/models.py:251: UserWarning: No training configuration found in save file: the model was *not* compiled. Compile it manually.
  warnings.warn('No training configuration found in save file: '
-----------------------./test/IMG_1563.JPG------------------------------------------
2018-01-04 18:13:22.903923: W tensorflow/core/framework/op_kernel.cc:1192] Unknown: KeyError: b'TEST'
Traceback (most recent call last):
  File "/root/anaconda3/envs/Python3_6/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1327, in _do_call
    return fn(*args)
  File "/root/anaconda3/envs/Python3_6/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1306, in _run_fn
    status, run_metadata)
  File "/root/anaconda3/envs/Python3_6/lib/python3.6/contextlib.py", line 88, in __exit__
    next(self.gen)
  File "/root/anaconda3/envs/Python3_6/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.UnknownError: KeyError: b'TEST'
         [[Node: rois/PyFunc = PyFunc[Tin=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_STRING, DT_INT32, DT_INT32], Tout=[DT_FLOAT, DT_FLOAT], token="pyfunc_0", _device="/job:localhost/replica:0/task:0/cpu:0"](Reshape_5, rpn_bbox_pred/Reshape, _arg_Placeholder_1_0_1, rois/PyFunc/input_3, rois/PyFunc/input_4, rois/PyFunc/input_5)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "demo.py", line 16, in <module>
    result,img = model.model(img,model='crnn')
  File "/home/lxw/python_prj/chinese-ocr-master/model.py", line 74, in model
    text_recs,tmp,img = text_detect(img)
  File "/home/lxw/python_prj/chinese-ocr-master/ctpn/text_detect.py", line 6, in text_detect
    scores, boxes,img = ctpn(img)
  File "/home/lxw/python_prj/chinese-ocr-master/ctpn/ctpn/model.py", line 33, in ctpn
    scores, boxes = test_ctpn(sess, net, img)
  File "ctpn/lib/fast_rcnn/test.py", line 172, in test_ctpn
    rois = sess.run([net.get_output('rois')[0]],feed_dict=feed_dict)
  File "/root/anaconda3/envs/Python3_6/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 895, in run
    run_metadata_ptr)
  File "/root/anaconda3/envs/Python3_6/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1124, in _run
    feed_dict_tensor, options, run_metadata)
  File "/root/anaconda3/envs/Python3_6/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1321, in _do_run
    options, run_metadata)
  File "/root/anaconda3/envs/Python3_6/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1340, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.UnknownError: KeyError: b'TEST'
         [[Node: rois/PyFunc = PyFunc[Tin=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_STRING, DT_INT32, DT_INT32], Tout=[DT_FLOAT, DT_FLOAT], token="pyfunc_0", _device="/job:localhost/replica:0/task:0/cpu:0"](Reshape_5, rpn_bbox_pred/Reshape, _arg_Placeholder_1_0_1, rois/PyFunc/input_3, rois/PyFunc/input_4, rois/PyFunc/input_5)]]

Caused by op 'rois/PyFunc', defined at:
  File "demo.py", line 2, in <module>
    import model
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "/home/lxw/python_prj/chinese-ocr-master/model.py", line 3, in <module>
    from ctpn.text_detect import text_detect
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "/home/lxw/python_prj/chinese-ocr-master/ctpn/text_detect.py", line 1, in <module>
    from ctpn.ctpn.model import ctpn
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "/home/lxw/python_prj/chinese-ocr-master/ctpn/ctpn/model.py", line 29, in <module>
    sess,saver,net = load_tf_model()
  File "/home/lxw/python_prj/chinese-ocr-master/ctpn/ctpn/model.py", line 22, in load_tf_model
    net = get_network("VGGnet_test")
  File "ctpn/lib/networks/factory.py", line 20, in get_network
    return VGGnet_test()
  File "ctpn/lib/networks/VGGnet_test.py", line 14, in __init__
    self.setup()
  File "ctpn/lib/networks/VGGnet_test.py", line 68, in setup
    .proposal_layer(_feat_stride, anchor_scales, 'TEST', name='rois'))
  File "ctpn/lib/networks/network.py", line 28, in layer_decorated
    layer_output = op(self, layer_input, *args, **kwargs)
  File "ctpn/lib/networks/network.py", line 241, in proposal_layer
    [tf.float32,tf.float32])
  File "/root/anaconda3/envs/Python3_6/lib/python3.6/site-packages/tensorflow/python/ops/script_ops.py", line 203, in py_func
    input=inp, token=token, Tout=Tout, name=name)
  File "/root/anaconda3/envs/Python3_6/lib/python3.6/site-packages/tensorflow/python/ops/gen_script_ops.py", line 36, in _py_func
    name=name)
  File "/root/anaconda3/envs/Python3_6/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "/root/anaconda3/envs/Python3_6/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2630, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/root/anaconda3/envs/Python3_6/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1204, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

UnknownError (see above for traceback): KeyError: b'TEST'
         [[Node: rois/PyFunc = PyFunc[Tin=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_STRING, DT_INT32, DT_INT32], Tout=[DT_FLOAT, DT_FLOAT], token="pyfunc_0", _device="/job:localhost/replica:0/task:0/cpu:0"](Reshape_5, rpn_bbox_pred/Reshape, _arg_Placeholder_1_0_1, rois/PyFunc/input_3, rois/PyFunc/input_4, rois/PyFunc/input_5)]]

**Comment by frankzhuo** [comment]
请问你是如何解决的？？？
