### ISSUE TITLE
你好，可否分享几张训练数据的样例图片，谢谢

### ISSUE THREAD

**Issue by fendaq** [chineseocr/chinese-ocr#4]
你好，我看你的中文识别效果特别好，我自己训练了几个版本都不怎么理想，中间有什么技巧可否分享一下。另外可否贴几张训练数据的图片上来，我怀疑是不是我的训练数据有问题，谢谢

**Comment by hsongNathanial** [comment]
你好我也run了一下你的text-detect-ctpn的文件，也遇到了和我运行这个文件时一样的问题


Traceback (most recent call last):
  File "demo.py", line 9, in <module>
    from lib.networks.factory import get_network
  File "/home/song/Desktop/detect/lib/__init__.py", line 1, in <module>
    import fast_rcnn
  File "/home/song/Desktop/detect/lib/fast_rcnn/__init__.py", line 9, in <module>
    from . import train
  File "/home/song/Desktop/detect/lib/fast_rcnn/train.py", line 6, in <module>
    from ..roi_data_layer.layer import RoIDataLayer
  File "/home/song/Desktop/detect/lib/roi_data_layer/__init__.py", line 7, in <module>
    import roidb
  File "/home/song/Desktop/detect/lib/roi_data_layer/roidb.py", line 19, in <module>
    from ..utils.cython_bbox import bbox_overlaps
  File "/home/song/Desktop/detect/lib/utils/__init__.py", line 7, in <module>
    from . import cython_nms
ImportError: cannot import name cython_nms

请问这个问题应该如何解决啊

**Comment by wenlihaoyu** [comment]
切换到lib目录，执行如下命令，编译，会生成对应的so文件。
cd ./ctpn/lib
python setup.py build  ##or make

**Comment by wenlihaoyu** [comment]
you can run this textgen.py gen train image line data
[textgen.py.txt](https://github.com/chineseocr/chinese-ocr/files/1466289/textgen.py.txt)

**Comment by hsongNathanial** [comment]
不管用啊，还是这个问题
