### ISSUE TITLE
pytorch训练问题

### ISSUE THREAD

**Issue by weiweili123** [chineseocr/chinese-ocr#42]
zou@zou:~/chinese-ocr-master/train/pytorch-train$ python crnn_main.py --cuda --adadelta
...
 batchSize=128, beta1=0.5, crnn='../pretrain-models/netCRNN.pth', cuda=True, displayInterval=50, experiment='./save_model', imgH=32, imgW=256, keep_ratio=False, lr=0.005, n_test_disp=1000, ngpu=1, nh=256, niter=1000000, random_sample=False, saveInterval=1000, trainroot='../data/lmdb/train', valInterval=50, valroot='../data/lmdb/val', workers=4)
mkdir: 无法创建目录"./save_model": 文件已存在
Random Seed:  6815
loading pretrained model from ../pretrain-models/netCRNN.pth
CRNN (
  (cnn): Sequential (
    (conv0): Conv2d(1, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (relu0): ReLU (inplace)
    (pooling0): MaxPool2d (size=(2, 2), stride=(2, 2), dilation=(1, 1))
    (conv1): Conv2d(64, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (relu1): ReLU (inplace)
    (pooling1): MaxPool2d (size=(2, 2), stride=(2, 2), dilation=(1, 1))
    (conv2): Conv2d(128, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (batchnorm2): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True)
    (relu2): ReLU (inplace)
    (conv3): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (relu3): ReLU (inplace)
    (pooling2): MaxPool2d (size=(2, 2), stride=(2, 1), dilation=(1, 1))
    (conv4): Conv2d(256, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (batchnorm4): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True)
    (relu4): ReLU (inplace)
    (conv5): Conv2d(512, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (relu5): ReLU (inplace)
    (pooling3): MaxPool2d (size=(2, 2), stride=(2, 1), dilation=(1, 1))
    (conv6): Conv2d(512, 512, kernel_size=(2, 2), stride=(1, 1))
    (batchnorm6): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True)
    (relu6): ReLU (inplace)
  )
  (rnn): Sequential (
    (0): BidirectionalLSTM (
      (rnn): LSTM(512, 256, bidirectional=True)
      (embedding): Linear (512 -> 256)
    )
    (1): BidirectionalLSTM (
      (rnn): LSTM(256, 256, bidirectional=True)
      (embedding): Linear (512 -> 5530)
    )
  )
)
Traceback (most recent call last):
  File "crnn_main.py", line 235, in <module>
    train_iter = iter(train_loader)
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/data/dataloader.py", line 301, in __iter__
    return DataLoaderIter(self)
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/data/dataloader.py", line 171, in __init__
    self._put_indices()
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/data/dataloader.py", line 210, in _put_indices
    indices = next(self.sample_iter, None)
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/data/sampler.py", line 115, in __iter__
    for idx in self.sampler:
  File "/home/zou/chinese-ocr-master/train/pytorch-train/dataset.py", line 99, in __iter__
    random_start = random.randint(0, len(self) - self.batch_size)
  File "/usr/lib/python2.7/random.py", line 242, in randint
    return self.randrange(a, b+1)
  File "/usr/lib/python2.7/random.py", line 218, in randrange
    raise ValueError, "empty range for randrange() (%d,%d, %d)" % (istart, istop, width)
ValueError: empty range for randrange() (0,-55, -55)

博主您好！我用pytorch进行训练的时候出现了上面这个问题，不知道是哪里的参数设置错误？

**Comment by wenlihaoyu** [comment]
你数据样本太小了，batch_size好像是128，len(self) - self.batch_size就小于0了

**Comment by weiweili123** [comment]
我把batch_size改成16以后可以继续运行，但是接下里出现了下面的错误：
zou@zou:~/chinese-ocr-master/train/pytorch-train$ python crnn_main.py --cuda
...
5996\u5e1b\u4fa8\u66f0\u59be\u6cd7', batchSize=16, beta1=0.5, crnn='../pretrain-models/netCRNN.pth', cuda=True, displayInterval=50, experiment='./save_model', imgH=32, imgW=256, keep_ratio=False, lr=0.005, n_test_disp=1000, ngpu=1, nh=256, niter=1000000, random_sample=False, saveInterval=1000, trainroot='../data/lmdb/train', valInterval=50, valroot='../data/lmdb/val', workers=4)
mkdir: 无法创建目录"./save_model": 文件已存在
...
/home/zou/chinese-ocr-master/train/pytorch-train/dataset.py:95: UserWarning: torch.range is deprecated in favor of torch.arange and will be removed in 0.3. Note that arange generates values in [start; end), not [start; end].
  batch_index = random_start + torch.range(0, self.batch_size - 1)
/home/zou/chinese-ocr-master/train/pytorch-train/dataset.py:100: UserWarning: torch.range is deprecated in favor of torch.arange and will be removed in 0.3. Note that arange generates values in [start; end), not [start; end].
  tail_index = random_start + torch.range(0, tail - 1)
Traceback (most recent call last):
  File "crnn_main.py", line 246, in <module>
    cost = trainBatch(crnn, criterion, optimizer)
  File "crnn_main.py", line 207, in trainBatch
    cost = criterion(preds, text, preds_size, length) / batch_size
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 224, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/warpctc_pytorch/__init__.py", line 60, in forward
    return _CTC()(acts, labels, act_lens, label_lens)
  File "/usr/local/lib/python2.7/dist-packages/warpctc_pytorch/__init__.py", line 26, in forward
    loss_func = warp_ctc.gpu_ctc if is_cuda else warp_ctc.cpu_ctc
AttributeError: 'module' object has no attribute 'gpu_ctc'

我的CTC的编译参考的是：https://github.com/SeanNaren/warp-ctc，不知道博主的CTC是怎样编译的？

**Comment by wenlihaoyu** [comment]
你没有编译对GPU的支持 
![image](https://user-images.githubusercontent.com/7800267/34572880-8361d012-f1ad-11e7-8e83-33ac411666d8.png)

**Comment by weiweili123** [comment]
zou@zou:~/chinese-ocr-master/train/pytorch-train$ python crnn_main.py --cuda --adadelta
...
 batchSize=16, beta1=0.5, crnn='../pretrain-models/netCRNN.pth', cuda=True, displayInterval=50, experiment='./save_model', imgH=32, imgW=256, keep_ratio=False, lr=0.005, n_test_disp=1000, ngpu=1, nh=256, niter=1000000, random_sample=False, saveInterval=1000, trainroot='../data/lmdb/train', valInterval=50, valroot='../data/lmdb/val', workers=4)
mkdir: 无法创建目录"./save_model": 文件已存在
Random Seed:  9308
loading pretrained model from ../pretrain-models/netCRNN.pth
CRNN (
  (cnn): Sequential (
    (conv0): Conv2d(1, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (relu0): ReLU (inplace)
    (pooling0): MaxPool2d (size=(2, 2), stride=(2, 2), dilation=(1, 1))
    (conv1): Conv2d(64, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (relu1): ReLU (inplace)
    (pooling1): MaxPool2d (size=(2, 2), stride=(2, 2), dilation=(1, 1))
    (conv2): Conv2d(128, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (batchnorm2): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True)
    (relu2): ReLU (inplace)
    (conv3): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (relu3): ReLU (inplace)
    (pooling2): MaxPool2d (size=(2, 2), stride=(2, 1), dilation=(1, 1))
    (conv4): Conv2d(256, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (batchnorm4): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True)
    (relu4): ReLU (inplace)
    (conv5): Conv2d(512, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (relu5): ReLU (inplace)
    (pooling3): MaxPool2d (size=(2, 2), stride=(2, 1), dilation=(1, 1))
    (conv6): Conv2d(512, 512, kernel_size=(2, 2), stride=(1, 1))
    (batchnorm6): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True)
    (relu6): ReLU (inplace)
  )
  (rnn): Sequential (
    (0): BidirectionalLSTM (
      (rnn): LSTM(512, 256, bidirectional=True)
      (embedding): Linear (512 -> 256)
    )
    (1): BidirectionalLSTM (
      (rnn): LSTM(256, 256, bidirectional=True)
      (embedding): Linear (512 -> 5530)
    )
  )
)
/home/zou/chinese-ocr-master/train/pytorch-train/dataset.py:95: UserWarning: torch.range is deprecated in favor of torch.arange and will be removed in 0.3. Note that arange generates values in [start; end), not [start; end].
  batch_index = random_start + torch.range(0, self.batch_size - 1)
/home/zou/chinese-ocr-master/train/pytorch-train/dataset.py:100: UserWarning: torch.range is deprecated in favor of torch.arange and will be removed in 0.3. Note that arange generates values in [start; end), not [start; end].
  tail_index = random_start + torch.range(0, tail - 1)

博主您好！ 然后训练的时候一直卡到上面这一步不动了。不加 --cudn 运行也是如此

**Comment by wenlihaoyu** [comment]
训练，每个50次迭代才会输出一次日志：“epoch:1,step:74431,Test loss:2.308770895,accuracy:0.74609375,train loss:2.29934602737”,你可以等一下

**Comment by weiweili123** [comment]
zou@zou:~/chinese-ocr-master/train/pytorch-train$ python crnn_main.py  --cuda --displayInterval=1  --adadelta 
batchSize=16, beta1=0.5, crnn='../pretrain-models/netCRNN.pth', cuda=True, displayInterval=1, experiment='./save_model', imgH=32, imgW=256, keep_ratio=False, lr=0.005, n_test_disp=1000, ngpu=1, nh=256, niter=1000000, random_sample=False, saveInterval=1000, trainroot='../data/lmdb/train', valInterval=50, valroot='../data/lmdb/val', workers=4)
mkdir: 无法创建目录"./save_model": 文件已存在
Random Seed:  4990
loading pretrained model from ../pretrain-models/netCRNN.pth
CRNN (
  (cnn): Sequential (
    (conv0): Conv2d(1, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (relu0): ReLU (inplace)
    (pooling0): MaxPool2d (size=(2, 2), stride=(2, 2), dilation=(1, 1))
    (conv1): Conv2d(64, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (relu1): ReLU (inplace)
    (pooling1): MaxPool2d (size=(2, 2), stride=(2, 2), dilation=(1, 1))
    (conv2): Conv2d(128, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (batchnorm2): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True)
    (relu2): ReLU (inplace)
    (conv3): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (relu3): ReLU (inplace)
    (pooling2): MaxPool2d (size=(2, 2), stride=(2, 1), dilation=(1, 1))
    (conv4): Conv2d(256, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (batchnorm4): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True)
    (relu4): ReLU (inplace)
    (conv5): Conv2d(512, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (relu5): ReLU (inplace)
    (pooling3): MaxPool2d (size=(2, 2), stride=(2, 1), dilation=(1, 1))
    (conv6): Conv2d(512, 512, kernel_size=(2, 2), stride=(1, 1))
    (batchnorm6): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True)
    (relu6): ReLU (inplace)
  )
  (rnn): Sequential (
    (0): BidirectionalLSTM (
      (rnn): LSTM(512, 256, bidirectional=True)
      (embedding): Linear (512 -> 256)
    )
    (1): BidirectionalLSTM (
      (rnn): LSTM(256, 256, bidirectional=True)
      (embedding): Linear (512 -> 5530)
    )
  )
)
/home/zou/chinese-ocr-master/train/pytorch-train/dataset.py:95: UserWarning: torch.range is deprecated in favor of torch.arange and will be removed in 0.3. Note that arange generates values in [start; end), not [start; end].
  batch_index = random_start + torch.range(0, self.batch_size - 1)
/home/zou/chinese-ocr-master/train/pytorch-train/dataset.py:100: UserWarning: torch.range is deprecated in favor of torch.arange and will be removed in 0.3. Note that arange generates values in [start; end), not [start; end].
  tail_index = random_start + torch.range(0, tail - 1)

设置--displayInterval=1仍然出现这种情况，但是显存占用了1037M

**Comment by wenlihaoyu** [comment]
那一步一步debug一下吧，我不能复现你的问题，看看是不是你的数据集太小，数据生成器可能会有一些问题。

**Comment by weiweili123** [comment]
好的，我自己生成些数据试试，感谢博主一直这么耐心的解答！

**Comment by ttool001** [comment]
There is bug in the code, it's comparing i to dispalyInterval. If u change it to compare with epoch it will print out the status of training

**Comment by favpdf** [comment]
这个问题主要是楼主用的pytorch版本跟作者的不一致导致的，在新版本的pytorch中，torch.range已经不在使用了，应该使用torch.arange。而两者表示的范围不一直，比如：torch.range（1, 3） 表示1, 2 ,3 而torch.arange(1, 2 , 3)则表示1, 2 没有最后的3.
