### ISSUE TITLE
博主gg windows 下 如何编译这些呢？

### ISSUE THREAD

**Issue by frankzhuo** [chineseocr/chinese-ocr#44]
C:\software\PythonWorkSpace\chinese-ocr-master\ctpn\lib\utils>python setup.py build_ext --inplac
e
running build_ext
Traceback (most recent call last):
  File "setup.py", line 125, in <module>
    cmdclass={'build_ext': custom_build_ext},
  File "C:\Python27\lib\distutils\core.py", line 151, in setup
    dist.run_commands()
  File "C:\Python27\lib\distutils\dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "C:\Python27\lib\distutils\dist.py", line 972, in run_command
    cmd_obj.run()
  File "C:\Python27\lib\site-packages\Cython\Distutils\old_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "C:\Python27\lib\distutils\command\build_ext.py", line 340, in run
    self.build_extensions()
  File "setup.py", line 74, in build_extensions
    customize_compiler_for_nvcc(self.compiler)
  File "setup.py", line 49, in customize_compiler_for_nvcc
    default_compiler_so = self.compiler_so
AttributeError: MSVCCompiler instance has no attribute 'compiler_so'

**Comment by wenlihaoyu** [comment]
windows没有研究过，建议还是在linux环境做吧
