### ISSUE TITLE
一个非常奇怪的问题

### ISSUE THREAD

**Issue by frankzhuo** [chineseocr/chinese-ocr#47]
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/software/PythonWorkSpace/chinese-ocr-master/demo.py", line 2, in <module>
    import model
  File "C:\software\PythonWorkSpace\chinese-ocr-master\model.py", line 3, in <module>
    from ctpn.text_detect import text_detect
  File "C:\software\PythonWorkSpace\chinese-ocr-master\ctpn\text_detect.py", line 1, in <module>
    from ctpn.ctpn.model import ctpn
  File "C:\software\PythonWorkSpace\chinese-ocr-master\ctpn\ctpn\model.py", line 31, in <module>
    sess,saver,net = load_tf_model()
  File "C:\software\PythonWorkSpace\chinese-ocr-master\ctpn\ctpn\model.py", line 28, in load_tf_model
    saver.restore(sess, os.path.join(os.getcwd(),"checkpoints\model_final_tf13.ckpt"))
  File "C:\software\anaconda3\lib\site-packages\tensorflow\python\training\saver.py", line 1560, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "C:\software\anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 895, in run
    run_metadata_ptr)
  File "C:\software\anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1124, in _run
    feed_dict_tensor, options, run_metadata)
  File "C:\software\anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1321, in _do_run
    options, run_metadata)
  File "C:\software\anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1340, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.NotFoundError: Key lstm_o/rnn/lstm_cell/kernel not found in checkpoint
	 [[Node: save/RestoreV2_28 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_arg_save/Const_0_0, save/RestoreV2_28/tensor_names, save/RestoreV2_28/shape_and_slices)]]

**Comment by wenlihaoyu** [comment]
应该是tensorflow版本的问题，lstm函数

**Comment by frankzhuo** [comment]
InvalidArgumentError (see above for traceback): Assign requires shapes of both tensors to match. lhs shape= [512,40] rhs shape= [128,40]

版本是tensorflow 1.3 脚本执行的

**Comment by frankzhuo** [comment]
File "C:\software\anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1139, in _do_call
    return fn(*args)
  File "C:\software\anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1121, in _run_fn
    status, run_metadata)
  File "C:\software\anaconda3\lib\contextlib.py", line 88, in __exit__
    next(self.gen)
  File "C:\software\anaconda3\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.DataLossError: file is too short to be an sstable
	 [[Node: save/RestoreV2 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_arg_save/Const_0_0, save/RestoreV2/tensor_names, save/RestoreV2/shape_and_slices)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/software/PythonWorkSpace/chinese-ocr-master/ctpn/ctpn/model.py", line 43, in <module>
    sess,saver,net = load_tf_model()
  File "C:/software/PythonWorkSpace/chinese-ocr-master/ctpn/ctpn/model.py", line 38, in load_tf_model
    saver.restore(sess, "C://software/PythonWorkSpace/chinese-ocr-master/checkpoints/model_final_tf13.ckpt")
  File "C:\software\anaconda3\lib\site-packages\tensorflow\python\training\saver.py", line 1548, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "C:\software\anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 789, in run
    run_metadata_ptr)
  File "C:\software\anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 997, in _run
    feed_dict_string, options, run_metadata)
  File "C:\software\anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1132, in _do_run
    target_list, options, run_metadata)
  File "C:\software\anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1152, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.DataLossError: file is too short to be an sstable
	 [[Node: save/RestoreV2 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_arg_save/Const_0_0, save/RestoreV2/tensor_names, save/RestoreV2/shape_and_slices)]]

Caused by op 'save/RestoreV2', defined at:
  File "C:/software/PythonWorkSpace/chinese-ocr-master/ctpn/ctpn/model.py", line 43, in <module>
    sess,saver,net = load_tf_model()
  File "C:/software/PythonWorkSpace/chinese-ocr-master/ctpn/ctpn/model.py", line 24, in load_tf_model
    saver = tf.train.Saver()
  File "C:\software\anaconda3\lib\site-packages\tensorflow\python\training\saver.py", line 1139, in __init__
    self.build()
  File "C:\software\anaconda3\lib\site-packages\tensorflow\python\training\saver.py", line 1170, in build
    restore_sequentially=self._restore_sequentially)
  File "C:\software\anaconda3\lib\site-packages\tensorflow\python\training\saver.py", line 691, in build
    restore_sequentially, reshape)
  File "C:\software\anaconda3\lib\site-packages\tensorflow\python\training\saver.py", line 407, in _AddRestoreOps
    tensors = self.restore_op(filename_tensor, saveable, preferred_shard)
  File "C:\software\anaconda3\lib\site-packages\tensorflow\python\training\saver.py", line 247, in restore_op
    [spec.tensor.dtype])[0])
  File "C:\software\anaconda3\lib\site-packages\tensorflow\python\ops\gen_io_ops.py", line 640, in restore_v2
    dtypes=dtypes, name=name)
  File "C:\software\anaconda3\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "C:\software\anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 2506, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "C:\software\anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 1269, in __init__
    self._traceback = _extract_stack()

DataLossError (see above for traceback): file is too short to be an sstable
	 [[Node: save/RestoreV2 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_arg_save/Const_0_0, save/RestoreV2/tensor_names, save/RestoreV2/shape_and_slices)]]
