### ISSUE TITLE
from crnn.crnn import crnnOcr出错

### ISSUE THREAD

**Issue by LiangHao92** [chineseocr/chinese-ocr#50]
之前使用keras版本，直接把model.py里面的`from crnn.crnn import crnnOcr`这句代码注释掉了，运行demo.py一切正常。现在想试试torch版本，将这句取消注释，发现代码运行不通，报错如下，请问这个是什么原因

`Traceback (most recent call last):
  File "demo.py", line 14, in <module>
    result,img = model.model(img,model='keras')
  File "/home/seven/chinese-ocr-master/model.py", line 75, in model
    text_recs,tmp,img = text_detect(img)
  File "/home/seven/chinese-ocr-master/ctpn/text_detect.py", line 6, in text_detect
    scores, boxes,img = ctpn(img)
  File "/home/seven/chinese-ocr-master/ctpn/ctpn/model.py", line 33, in ctpn
    scores, boxes = test_ctpn(sess, net, img)
  File "ctpn/lib/fast_rcnn/test.py", line 171, in test_ctpn
    rois = sess.run([net.get_output('rois')[0]],feed_dict=feed_dict)
  File "/home/seven/anaconda2/envs/crnn/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 895, in run
    run_metadata_ptr)
  File "/home/seven/anaconda2/envs/crnn/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1124, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/seven/anaconda2/envs/crnn/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1321, in _do_run
    options, run_metadata)
  File "/home/seven/anaconda2/envs/crnn/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1340, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InternalError: Blas GEMM launch failed : a.shape=(1739, 512), b.shape=(512, 128), m=1739, n=128, k=512
	 [[Node: lstm_o/MatMul = MatMul[T=DT_FLOAT, transpose_a=false, transpose_b=false, _device="/job:localhost/replica:0/task:0/gpu:0"](Reshape, lstm_o/weights/read)]]
	 [[Node: rois/Reshape/_81 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_412_rois/Reshape", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]

Caused by op u'lstm_o/MatMul', defined at:
  File "demo.py", line 2, in <module>
    import model
  File "/home/seven/chinese-ocr-master/model.py", line 4, in <module>
    from ctpn.text_detect import text_detect
  File "/home/seven/chinese-ocr-master/ctpn/text_detect.py", line 1, in <module>
    from ctpn.model import ctpn
  File "/home/seven/chinese-ocr-master/ctpn/ctpn/model.py", line 29, in <module>
    sess,saver,net = load_tf_model()
  File "/home/seven/chinese-ocr-master/ctpn/ctpn/model.py", line 22, in load_tf_model
    net = get_network("VGGnet_test")
  File "ctpn/lib/networks/factory.py", line 20, in get_network
    return VGGnet_test()
  File "ctpn/lib/networks/VGGnet_test.py", line 14, in __init__
    self.setup()
  File "ctpn/lib/networks/VGGnet_test.py", line 43, in setup
    (self.feed('rpn_conv/3x3').lstm(512, 128, name='lstm_o'))
  File "ctpn/lib/networks/network.py", line 28, in layer_decorated
    layer_output = op(self, layer_input, *args, **kwargs)
  File "ctpn/lib/networks/network.py", line 133, in lstm
    _H = tf.matmul(input, kernel) + biases
  File "/home/seven/anaconda2/envs/crnn/lib/python2.7/site-packages/tensorflow/python/ops/math_ops.py", line 1844, in matmul
    a, b, transpose_a=transpose_a, transpose_b=transpose_b, name=name)
  File "/home/seven/anaconda2/envs/crnn/lib/python2.7/site-packages/tensorflow/python/ops/gen_math_ops.py", line 1289, in _mat_mul
    transpose_b=transpose_b, name=name)
  File "/home/seven/anaconda2/envs/crnn/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "/home/seven/anaconda2/envs/crnn/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2630, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/home/seven/anaconda2/envs/crnn/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1204, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InternalError (see above for traceback): Blas GEMM launch failed : a.shape=(1739, 512), b.shape=(512, 128), m=1739, n=128, k=512
	 [[Node: lstm_o/MatMul = MatMul[T=DT_FLOAT, transpose_a=false, transpose_b=false, _device="/job:localhost/replica:0/task:0/gpu:0"](Reshape, lstm_o/weights/read)]]
	 [[Node: rois/Reshape/_81 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_412_rois/Reshape", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]`

**Comment by wenlihaoyu** [comment]
重新更新代码
