### ISSUE TITLE
CUDA版本是8，'dict' object has no attribute 'iteritems'

### ISSUE THREAD

**Issue by JiangKui007** [chineseocr/chinese-ocr#51]
python3运行build时，跳出错误：
完整错误信息：
python setup.py build
Traceback (most recent call last):
  File "setup.py", line 55, in <module>
    CUDA = locate_cuda()
  File "setup.py", line 50, in locate_cuda
    for k, v in cudaconfig.iteritems():
AttributeError: 'dict' object has no attribute 'iteritems'

cuda已经安装，easydict已经安装过了.

**Comment by JiangKui007** [comment]
Python3.5中：iteritems变为items
