### ISSUE TITLE
启动demo后显示Using TensorFlow backend.

### ISSUE THREAD

**Issue by JiangKui007** [chineseocr/chinese-ocr#54]
`2018-01-12 10:40:11.459627: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2018-01-12 10:40:11.459678: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2018-01-12 10:40:11.459690: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2018-01-12 10:40:11.459711: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
2018-01-12 10:40:11.459742: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
2018-01-12 10:40:11.832464: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:893] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2018-01-12 10:40:11.832854: I tensorflow/core/common_runtime/gpu/gpu_device.cc:955] Found device 0 with properties: 
name: Tesla P100-PCIE-16GB
major: 6 minor: 0 memoryClockRate (GHz) 1.3285
pciBusID 0000:00:08.0
Total memory: 15.89GiB
Free memory: 15.60GiB
2018-01-12 10:40:11.832891: I tensorflow/core/common_runtime/gpu/gpu_device.cc:976] DMA: 0 
2018-01-12 10:40:11.832906: I tensorflow/core/common_runtime/gpu/gpu_device.cc:986] 0:   Y 
2018-01-12 10:40:11.832921: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1045] Creating TensorFlow device (/gpu:0) -> (device: 0, name: Tesla P100-PCIE-16GB, pci bus id: 0000:00:08.0)
Tensor("Placeholder:0", shape=(?, ?, ?, 3), dtype=float32)
Tensor("conv5_3/conv5_3:0", shape=(?, ?, ?, 512), dtype=float32)
Tensor("rpn_conv/3x3/rpn_conv/3x3:0", shape=(?, ?, ?, 512), dtype=float32)
WARNING:tensorflow:<tensorflow.python.ops.rnn_cell_impl.BasicLSTMCell object at 0x7fa12a3e8cd0>: Using a concatenated state is slower and will soon be deprecated.  Use state_is_tuple=True.
Tensor("lstm_o/Reshape:0", shape=(?, ?, ?, 128), dtype=float32)
Tensor("lstm_o/Reshape:0", shape=(?, ?, ?, 128), dtype=float32)
Tensor("rpn_cls_score/Reshape:0", shape=(?, ?, ?, 20), dtype=float32)
Tensor("rpn_cls_prob:0", shape=(?, ?, ?, ?), dtype=float32)
Tensor("Reshape_5:0", shape=(?, ?, ?, 20), dtype=float32)
Tensor("rpn_bbox_pred/Reshape:0", shape=(?, ?, ?, 40), dtype=float32)
Tensor("Placeholder_1:0", shape=(?, 3), dtype=float32)
Using TensorFlow backend.`

cpu占用率很高，终端不动了。这是正确运行了吗？

**Comment by fathomguru** [comment]
我也是楼上这种情况，跑了一天都还是这样。楼上解决问题了吗？

**Comment by wenlihaoyu** [comment]
更新一下代码

**Comment by fathomguru** [comment]
谢谢你的建议，我更新代码后，运行sh setup.sh 没有问题，然后直接运行python demo.py, 依然是一直显示Using TensorFlow backend。
恳请你指点，谢谢！
具体运行信息如下：

xm@xm:~/project/chinese-ocr-master$ python demo.py
2018-01-19 20:08:20.885625: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2018-01-19 20:08:20.885645: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2018-01-19 20:08:20.885650: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2018-01-19 20:08:20.885654: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
2018-01-19 20:08:20.885672: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
2018-01-19 20:08:20.976835: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:893] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2018-01-19 20:08:20.977087: I tensorflow/core/common_runtime/gpu/gpu_device.cc:955] Found device 0 with properties: 
name: GeForce GTX 1070
major: 6 minor: 1 memoryClockRate (GHz) 1.7465
pciBusID 0000:01:00.0
Total memory: 7.92GiB
Free memory: 7.61GiB
2018-01-19 20:08:20.977100: I tensorflow/core/common_runtime/gpu/gpu_device.cc:976] DMA: 0 
2018-01-19 20:08:20.977105: I tensorflow/core/common_runtime/gpu/gpu_device.cc:986] 0:   Y 
2018-01-19 20:08:20.977125: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1045] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 1070, pci bus id: 0000:01:00.0)
Tensor("Placeholder:0", shape=(?, ?, ?, 3), dtype=float32)
Tensor("conv5_3/conv5_3:0", shape=(?, ?, ?, 512), dtype=float32)
Tensor("rpn_conv/3x3/rpn_conv/3x3:0", shape=(?, ?, ?, 512), dtype=float32)
Tensor("lstm_o/Reshape_2:0", shape=(?, ?, ?, 512), dtype=float32)
Tensor("lstm_o/Reshape_2:0", shape=(?, ?, ?, 512), dtype=float32)
Tensor("rpn_cls_score/Reshape_1:0", shape=(?, ?, ?, 20), dtype=float32)
Tensor("rpn_cls_prob:0", shape=(?, ?, ?, ?), dtype=float32)
Tensor("Reshape_2:0", shape=(?, ?, ?, 20), dtype=float32)
Tensor("rpn_bbox_pred/Reshape_1:0", shape=(?, ?, ?, 40), dtype=float32)
Tensor("Placeholder_1:0", shape=(?, 3), dtype=float32)
Using TensorFlow backend.

**Comment by wenlihaoyu** [comment]
测试一下，你的tensorflow是否安装正确，或者单独加载一下文本检测模型

**Comment by chengjunjiecn** [comment]
我也出现同样问题，tensorflow正确，单独加载文本检测正确

**Comment by chengjunjiecn** [comment]
Failed to get matching files on /chinese-ocr/ctpn/checkpoints/model_final.ckpt: Not found: chinese-ocr/ctpn/checkpoints

**Comment by wenlihaoyu** [comment]
@chengjunjiecn 重新更新代码

**Comment by chengjunjiecn** [comment]
还是报错。

具体日志

(chinese-ocr) myname@guest-Super-Server:~/myname_share/test/chinese-ocr/ctpn$ ls
ctpn  data  __init__.py  __init__.pyc  lib  models  text_detect.py  text_detect.pyc
(chinese-ocr) myname@guest-Super-Server:~/myname_share/test/chinese-ocr/ctpn$ git pull
Already up-to-date.
(chinese-ocr) myname@guest-Super-Server:~/myname_share/test/chinese-ocr/ctpn$ python ctpn/demo.py
2018-01-22 17:35:55.248394: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2018-01-22 17:35:55.248439: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2018-01-22 17:35:55.248454: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2018-01-22 17:35:55.248462: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
2018-01-22 17:35:55.248471: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
2018-01-22 17:35:55.921442: I tensorflow/core/common_runtime/gpu/gpu_device.cc:955] Found device 0 with properties:
name: TITAN Xp
major: 6 minor: 1 memoryClockRate (GHz) 1.582
pciBusID 0000:02:00.0
Total memory: 11.90GiB
Free memory: 11.74GiB
2018-01-22 17:35:55.921518: I tensorflow/core/common_runtime/gpu/gpu_device.cc:976] DMA: 0
2018-01-22 17:35:55.921533: I tensorflow/core/common_runtime/gpu/gpu_device.cc:986] 0:   Y
2018-01-22 17:35:55.921549: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1045] Creating TensorFlow device (/gpu:0) -> (device: 0, name: TITAN Xp, pci bus id: 0000:02:00.0)
Tensor("Placeholder:0", shape=(?, ?, ?, 3), dtype=float32)
Tensor("conv5_3/conv5_3:0", shape=(?, ?, ?, 512), dtype=float32)
Tensor("rpn_conv/3x3/rpn_conv/3x3:0", shape=(?, ?, ?, 512), dtype=float32)
/home/myname/anaconda2/envs/chinese-ocr/lib/python2.7/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Tensor("lstm_o/Reshape_2:0", shape=(?, ?, ?, 512), dtype=float32)
Tensor("lstm_o/Reshape_2:0", shape=(?, ?, ?, 512), dtype=float32)
2018-01-22 17:36:00.089483: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on /home/myname/myname_share/test/chinese-ocr/ctpn/checkpoints/model_final.ckpt: Not found: /home/myname/myname_share/test/chinese-ocr/ctpn/checkpoints
Loading network VGGnet_test...
Traceback (most recent call last):
  File "ctpn/demo.py", line 89, in <module>
    saver.restore(sess, os.path.join(os.getcwd(),"checkpoints/model_final.ckpt"))
  File "/home/myname/anaconda2/envs/chinese-ocr/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1560, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/home/myname/anaconda2/envs/chinese-ocr/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 895, in run
    run_metadata_ptr)
  File "/home/myname/anaconda2/envs/chinese-ocr/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1124, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/myname/anaconda2/envs/chinese-ocr/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1321, in _do_run
    options, run_metadata)
  File "/home/myname/anaconda2/envs/chinese-ocr/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1340, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Unsuccessful TensorSliceReader constructor: Failed to get matching files on /home/myname/myname_share/test/chinese-ocr/ctpn/checkpoints/model_final.ckpt: Not found: /home/myname/myname_share/test/chinese-ocr/ctpn/checkpoints
         [[Node: save/RestoreV2_5 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_arg_save/Const_0_0, save/RestoreV2_5/tensor_names, save/RestoreV2_5/shape_and_slices)]]

Caused by op u'save/RestoreV2_5', defined at:
  File "ctpn/demo.py", line 88, in <module>
    saver = tf.train.Saver()
  File "/home/myname/anaconda2/envs/chinese-ocr/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1140, in __init__
    self.build()
  File "/home/myname/anaconda2/envs/chinese-ocr/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1172, in build
    filename=self._filename)
  File "/home/myname/anaconda2/envs/chinese-ocr/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 688, in build
    restore_sequentially, reshape)
  File "/home/myname/anaconda2/envs/chinese-ocr/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 407, in _AddRestoreOps
    tensors = self.restore_op(filename_tensor, saveable, preferred_shard)
  File "/home/myname/anaconda2/envs/chinese-ocr/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 247, in restore_op
    [spec.tensor.dtype])[0])
  File "/home/myname/anaconda2/envs/chinese-ocr/lib/python2.7/site-packages/tensorflow/python/ops/gen_io_ops.py", line 663, in restore_v2
    dtypes=dtypes, name=name)
  File "/home/myname/anaconda2/envs/chinese-ocr/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "/home/myname/anaconda2/envs/chinese-ocr/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2630, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/home/myname/anaconda2/envs/chinese-ocr/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1204, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): Unsuccessful TensorSliceReader constructor: Failed to get matching files on /home/myname/myname_share/test/chinese-ocr/ctpn/checkpoints/model_final.ckpt: Not found: /home/myname/myname_share/test/chinese-ocr/ctpn/checkpoints
         [[Node: save/RestoreV2_5 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_arg_save/Const_0_0, save/RestoreV2_5/tensor_names, save/RestoreV2_5/shape_and_slices)]]

(chinese-ocr) myname@guest-Super-Server:~/myname_share/test/chinese-ocr/ctpn$

**Comment by JiangKui007** [comment]
单独加载文本检测模型，报错：
`InvalidArgumentError (see above for traceback): Unsuccessful TensorSliceReader constructor: Failed to get matching files on /root/20180125/chinese-ocr/ctpn/checkpoints/model_final.ckpt: Not found: /root/20180125/chinese-ocr/ctpn/checkpoints
	 [[Node: save/RestoreV2 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_arg_save/Const_0_0, save/RestoreV2/tensor_names, save/RestoreV2/shape_and_slices)]]
	 [[Node: save/RestoreV2_1/_75 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/gpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_154_save/RestoreV2_1", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/gpu:0"]()]]

`

**Comment by JiangKui007** [comment]
修改demo.py 中第89行 将地址更换为“models/VGGnet_fast_rcnn_iter_470000.ckpt”
报错信息变为：

> ResourceExhaustedError (see above for traceback): OOM when allocating tensor with shape[1,900,900,64]
	 [[Node: conv1_1/Conv2D = Conv2D[T=DT_FLOAT, data_format="NHWC", padding="SAME", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/gpu:0"](_arg_Placeholder_0_0/_77, conv1_1/weights/read)]]
	 [[Node: Reshape_2/_79 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_496_Reshape_2", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]

**Comment by wenlihaoyu** [comment]
你的GPU内存，把图片尺寸弄小一点

**Comment by JiangKui007** [comment]
尝试升级了tensorflow 貌似解决了这个问题。
这句升级语句也许可以加入依赖包安装过程中？

> pip install tensorflow --upgrade

**Comment by JiangKui007** [comment]
在尝试训练pytorch过程中，遇到了import错误，编译安装了torch和warp-ctc.安装完成后

`python crnn_main.py`
仍然报错：

> ImportError: No module named warpctc_pytorch

**Comment by JiangKui007** [comment]
在angle安装了楼主提供的h5文件，能run起来了，但是识别结果非常差，大部分是乱码。需要重新训练？

**Comment by JiangKui007** [comment]
找了原因，warp-ctc要用pytorch版本的。地址如下：
https://github.com/SeanNaren/warp-ctc

**Comment by JiangKui007** [comment]
开始pytorch训练后报错：
mkdir: cannot create directory ‘./save_model’: File exists
Random Seed:  6005
Traceback (most recent call last):
  File "crnn_main.py", line 75, in <module>
    collate_fn=dataset.alignCollate(imgH=opt.imgH, imgW=opt.imgW, keep_ratio=opt.keep_ratio))
  File "/root/anaconda2/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 296, in __init__
    raise ValueError('sampler is mutually exclusive with shuffle')
ValueError: sampler is mutually exclusive with shuffle

**Comment by chengjunjiecn** [comment]
我也跑起来了，识别效果不错啊，demo.ipynb

**Comment by JiangKui007** [comment]
关于angle模型，可以查看这个issue #65
