### ISSUE TITLE
pytorch训练问题

### ISSUE THREAD

**Issue by ADiffM** [chineseocr/chinese-ocr#59]
用pytorch训练的时候出现如下错误，求解：
Traceback (most recent call last):
  File "crnn_main.py", line 75, in <module>
    collate_fn=dataset.alignCollate(imgH=opt.imgH, imgW=opt.imgW, keep_ratio=opt.keep_ratio))
  File "/home/kp/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 296, in __init__
    raise ValueError('sampler is mutually exclusive with shuffle')
ValueError: sampler is mutually exclusive with shuffle

**Comment by wenlihaoyu** [comment]
我是用python2.7训练，3.6可能会有一些问题

**Comment by kertansul** [comment]
@ADiffM 剛遇到一樣的Error, 似乎是 pytorch 版本問題

[源代碼](https://github.com/pytorch/pytorch/blob/master/torch/utils/data/dataloader.py#L387) 跟 [crnn_main.py](https://github.com/chineseocr/chinese-ocr/blob/master/train/pytorch-train/crnn_main.py#L71) 配合著看
發現 `opt.random_sample` 如果沒有被設為 `true` 這個 error 就會被觸發

在 `python crnn_main.py` 後加上 `--random_sample` 就沒問題了
