### ISSUE TITLE
更新代码后出现IOError: Unable to open file (file signature not found)

### ISSUE THREAD

**Issue by YCG09** [chineseocr/chinese-ocr#60]
你好，

今天更新角度检测部分的代码后，运行demo.py时出现下面错误，不知道是不是h5文件有问题

Traceback (most recent call last):
  File "demo.py", line 2, in <module>
    import model
  File "/home/ubuntu/Documents/ycg09/chinese-ocr/model.py", line 5, in <module>
    from angle.predict import predict as angle_detect##文字方向检测
  File "/home/ubuntu/Documents/ycg09/chinese-ocr/angle/predict.py", line 23, in <module>
    model = load()
  File "/home/ubuntu/Documents/ycg09/chinese-ocr/angle/predict.py", line 21, in load
    model.load_weights('./angle/modelAngle.h5')
  File "/home/ubuntu/anaconda3/envs/tf_1.3.0_py_2.7/lib/python2.7/site-packages/keras/engine/topology.py", line 2613, in load_weights
    f = h5py.File(filepath, mode='r')
  File "/home/ubuntu/anaconda3/envs/tf_1.3.0_py_2.7/lib/python2.7/site-packages/h5py/_hl/files.py", line 269, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
  File "/home/ubuntu/anaconda3/envs/tf_1.3.0_py_2.7/lib/python2.7/site-packages/h5py/_hl/files.py", line 99, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 78, in h5py.h5f.open
IOError: Unable to open file (file signature not found)

**Comment by wenlihaoyu** [comment]
用git lfs clone 下载代码，可能是模型对应的h5文件没有下载完，或者手动下载对应的h5文件，放在对应的目录

**Comment by YCG09** [comment]
@wenlihaoyu 谢谢，正如你所说，问题已解决
