### ISSUE TITLE
pytorch训练报未知错误

### ISSUE THREAD

**Issue by xiaoC1314** [chineseocr/chinese-ocr#87]
python3.6 
执行 python crnn_main.py --random_sample 是报以下错误

CRNN.pth', cuda=False, displayInterval=50, experiment='./save_model', imgH=32, imgW=256, keep_ratio=False, lr=0.005, n_test_disp=1000, ngpu=1, nh=256, niter=1000000, random_sample=True, saveInterval=1000, trainroot='../data/lmdb/train', valInterval=50, valroot='../data/lmdb/val', workers=4)
mkdir: cannot create directory ‘./save_model’: File exists
Random Seed:  1536
loading pretrained model from ../pretrain-models/netCRNN.pth
THCudaCheck FAIL file=/opt/pytorch/aten/src/THC/THCGeneral.c line=70 error=30 : unknown error
Traceback (most recent call last):
  File "crnn_main.py", line 102, in <module>
    crnn.load_state_dict(torch.load(opt.crnn))
  File "/root/anaconda3/lib/python3.6/site-packages/torch/serialization.py", line 267, in load
    return _load(f, map_location, pickle_module)
  File "/root/anaconda3/lib/python3.6/site-packages/torch/serialization.py", line 426, in _load
    result = unpickler.load()
  File "/root/anaconda3/lib/python3.6/site-packages/torch/serialization.py", line 395, in persistent_load
    data_type(size), location)
  File "/root/anaconda3/lib/python3.6/site-packages/torch/serialization.py", line 87, in default_restore_location
    result = fn(storage, location)
  File "/root/anaconda3/lib/python3.6/site-packages/torch/serialization.py", line 69, in _cuda_deserialize
    return obj.cuda(device)
  File "/root/anaconda3/lib/python3.6/site-packages/torch/_utils.py", line 61, in _cuda
    with torch.cuda.device(device):
  File "/root/anaconda3/lib/python3.6/site-packages/torch/cuda/__init__.py", line 218, in __enter__
    _lazy_init()
  File "/root/anaconda3/lib/python3.6/site-packages/torch/cuda/__init__.py", line 153, in _lazy_init
    torch._C._cuda_init()
RuntimeError: cuda runtime error (30) : unknown error at /opt/pytorch/aten/src/THC/THCGeneral.c:70

只知道报了未知错误。

**Comment by xiaoC1314** [comment]
用gpu训练，然后没有显卡

**Comment by wenlihaoyu** [comment]
训练的时候把 --cuda 关掉

**Comment by xiaoC1314** [comment]
感谢你：
      已经处理了。切换成cpu模式训练的时候，
      而且crnn.load_state_dict(torch.load(opt.crnn))也要改了。
    不过已经有人把问题贴出来了。再次感谢。



chenh2020@sina.com
 
发件人： lywen
发送时间： 2018-02-09 10:46
收件人： chineseocr/chinese-ocr
抄送： xiaoC1314; State change
主题： Re: [chineseocr/chinese-ocr] pytorch训练报未知错误 (#87)
训练的时候把 --cuda 关掉
―
