### ISSUE TITLE
运行demo.py出错

### ISSUE THREAD

**Issue by mountainguan** [chineseocr/chinese-ocr#96]
明明都装了tensorflow1.3还是这样子
```
Traceback (most recent call last):
  File "demo.py", line 2, in <module>
    import model
  File "/home/renaren/chinese-ocr/model.py", line 3, in <module>
    from ctpn.text_detect import text_detect
  File "/home/renaren/chinese-ocr/ctpn/text_detect.py", line 1, in <module>
    from ctpn.model import ctpn
  File "/home/renaren/chinese-ocr/ctpn/ctpn/__init__.py", line 1, in <module>
    import text_proposal_connector
  File "/home/renaren/chinese-ocr/ctpn/ctpn/text_proposal_connector.py", line 2, in <module>
    from other import clip_boxes
  File "/home/renaren/chinese-ocr/ctpn/ctpn/other.py", line 4, in <module>
    from matplotlib import cm
  File "/home/renaren/.local/lib/python2.7/site-packages/matplotlib/__init__.py", line 128, in <module>
    from matplotlib.rcsetup import defaultParams, validate_backend, cycler
  File "/home/renaren/.local/lib/python2.7/site-packages/matplotlib/rcsetup.py", line 29, in <module>
    from matplotlib.fontconfig_pattern import parse_fontconfig_pattern
  File "/home/renaren/.local/lib/python2.7/site-packages/matplotlib/fontconfig_pattern.py", line 32, in <module>
    from backports.functools_lru_cache import lru_cache
ImportError: No module named functools_lru_cache
```

再附上pip install matplotlib提示的内容
```
Requirement already satisfied: matplotlib in /home/renaren/.local/lib/python2.7/site-packages
Requirement already satisfied: python-dateutil>=2.1 in /home/renaren/.local/lib/python2.7/site-packages (from matplotlib)
Requirement already satisfied: subprocess32 in /home/renaren/.local/lib/python2.7/site-packages (from matplotlib)
Requirement already satisfied: cycler>=0.10 in /home/renaren/.local/lib/python2.7/site-packages (from matplotlib)
Requirement already satisfied: six>=1.10 in /home/renaren/.local/lib/python2.7/site-packages (from matplotlib)
Requirement already satisfied: backports.functools-lru-cache in /home/renaren/.local/lib/python2.7/site-packages (from matplotlib)
Requirement already satisfied: pytz in /home/renaren/.local/lib/python2.7/site-packages (from matplotlib)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /home/renaren/.local/lib/python2.7/site-packages (from matplotlib)
Requirement already satisfied: numpy>=1.7.1 in /home/renaren/.local/lib/python2.7/site-packages (from matplotlib)
```

**Comment by mountainguan** [comment]
刚刚conda install backports.functools_lru_cache 解决了....
